// pnpm gen:types — taskd がコミットする docs/api/v1/api-v1.schema.json から app/taskd/types.ts を生成する（docs/taskd-api-v1.md §7）。
// 実行時に taskd の API は呼ばない。$TASKD_REPO（既定は gui/ の親 = リポジトリの根。ADR-0020）のファイルだけを読む。
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const taskdRepo = path.resolve(process.env.TASKD_REPO ?? path.join(root, ".."));
const schema = path.join(taskdRepo, "docs", "api", "v1", "api-v1.schema.json");
const out = path.join(root, "app", "taskd", "types.ts");

if (!existsSync(schema)) {
  console.error(`gen-types: schema not found: ${schema} (set TASKD_REPO)`);
  process.exit(2);
}
execFileSync(
  "pnpm",
  ["exec", "json2ts", "-i", schema, "-o", out, "--additionalProperties=false", "--bannerComment", BANNER()],
  { stdio: "inherit", cwd: root },
);
function BANNER() {
  return "/* eslint-disable */\n/**\n * Generated by `pnpm gen:types` from taskd's docs/api/v1/api-v1.schema.json (taskd HTTP API v1).\n * DO NOT EDIT. Re-run `pnpm gen:types` after taskd updates the schema.\n */";
}
