// pnpm gen:types — celeris がコミットする docs/api/v1/api-v1.schema.json から app/celeris/types.ts を生成する（docs/celeris-api-v1.md §7）。
// 実行時に celeris の API は呼ばない。$CELERIS_REPO（既定は gui/ の親 = リポジトリの根。ADR-0020）のファイルだけを読む。
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const celerisRepo = path.resolve(process.env.CELERIS_REPO ?? path.join(root, ".."));
const schema = path.join(celerisRepo, "docs", "api", "v1", "api-v1.schema.json");
const out = path.join(root, "app", "celeris", "types.ts");

if (!existsSync(schema)) {
  console.error(`gen-types: schema not found: ${schema} (set CELERIS_REPO)`);
  process.exit(2);
}
execFileSync(
  "pnpm",
  ["exec", "json2ts", "-i", schema, "-o", out, "--additionalProperties=false", "--bannerComment", BANNER()],
  { stdio: "inherit", cwd: root },
);
function BANNER() {
  return "/* eslint-disable */\n/**\n * Generated by `pnpm gen:types` from celeris's docs/api/v1/api-v1.schema.json (celeris HTTP API v1).\n * DO NOT EDIT. Re-run `pnpm gen:types` after celeris updates the schema.\n */";
}
