/* eslint-disable */
/**
 * Generated by `pnpm gen:types` from taskd's docs/api/v1/api-v1.schema.json (taskd HTTP API v1).
 * DO NOT EDIT. Re-run `pnpm gen:types` after taskd updates the schema.
 */

/**
 * `POST /api/v1/providers/{id}/check` の結果（ADR-0017 D2）。
 */
export type ProviderCheckResult = "ok" | "auth_failed" | "throttled" | "spawn_failed";
/**
 * ADR-0002 D1 の状態集合。終端は `done | failed | cancelled`。
 */
export type Status = "draft" | "ready" | "running" | "blocked" | "reviewing" | "done" | "failed" | "cancelled";
/**
 * DESIGN §5.4 の `WorkerHint`。
 */
export type Tier = "frontier" | "standard" | "cheap";
/**
 * タスクの一意識別子（ULID）。DESIGN §4.1。
 */
export type TaskId = string;
export type InFlightKind = "worker" | "reviewer";
/**
 * DESIGN §4.3 の `Event`（追記専用）。ADR-0002 D2: `Transitioned` は遷移の
 * *結果* を記録するものであり、`transition()` の入力（`Trigger`）とは別物。
 * `JsonSchema` は ADR-0013 D8: `docs/api/v1/event.schema.json`（`EventRow` 経由）の契約に使う。
 */
export type Event =
  | {
      task: Task;
      type: "created";
    }
  | {
      from: Status;
      reason: string;
      to: Status;
      type: "transitioned";
    }
  | {
      /**
       * プール（`account_pool = true`）で選ばれた Claude アカウントの id（ADR-0024 D4）。プールを使わない
       * プロバイダ・導入前のイベントには無い。`provider`（アダプタ×プロバイダ行）とは別軸。
       */
      account?: string | null;
      adapter: string;
      model: string;
      /**
       * どのプロバイダ（= アカウント）で実行したか（ADR-0012 D1）。導入前のイベントには無いので任意。
       */
      provider?: string | null;
      /**
       * ADR-0014 D1: `None` はワーカー run、`Some(Reviewer)` は Reviewer run（ワーカー run に `Some(Worker)` は書かない）。
       */
      role?: RunRole | null;
      run_id: string;
      /**
       * ADR-0016 D1: run 開始時のタスクの役割名（`Task.role`）。役割の無いタスク・導入前のイベントには無い。
       */
      task_role?: string | null;
      type: "worker_started";
    }
  | {
      msg: string;
      run_id: string;
      type: "worker_progress";
    }
  | {
      artifact: ArtifactRef;
      run_id: string;
      type: "artifact_produced";
    }
  | {
      outcome: string;
      /**
       * ADR-0014 D1: `WorkerStarted.role` と同じ（`None` はワーカー run）。
       */
      role?: RunRole | null;
      run_id: string;
      type: "worker_finished";
      usage?: Usage | null;
    }
  | {
      criterion_idx: number;
      pass: boolean;
      reason: string;
      run_id: string;
      type: "review_verdict";
    }
  | {
      type: "approval_requested";
    }
  | {
      approved: boolean;
      by: string;
      note?: string | null;
      type: "approval_decided";
    }
  | {
      answer: string;
      question: string;
      type: "answered";
    }
  | {
      /**
       * この質問のきっかけになった run（親の直近の run）。
       */
      run_id: string;
      text: string;
      type: "question_raised";
    }
  | {
      run_id: string;
      task_ids: TaskId[];
      type: "delegated";
    }
  | {
      cluster: string;
      /**
       * `~/.ssh/config` の `Host` 名（`scripts/cluster-login.sh <host>` を案内するため）。第 1 段階の行には無いので任意。
       */
      host?: string;
      reason: string;
      type: "cluster_unavailable";
    }
  | {
      provider: string;
      /**
       * 供給側失敗の種別（ADR-0013 D9）: `throttled | auth_failed | exhausted | spawn`。
       * 導入前のイベントには無いので任意。このバリアントを構築している箇所は現状無い
       * （`grep -rn ProviderThrottled crates` で確認済み）。
       */
      reason?: string | null;
      type: "provider_throttled";
      until: string;
    };
/**
 * DESIGN §5.3/§5.7 の `Check` 種別。
 */
export type Check =
  | {
      cmd: string;
      expect_exit: number;
      type: "command";
    }
  | {
      name: string;
      type: "artifact_exists";
    }
  | {
      type: "reviewer";
    }
  | {
      type: "human";
    };
/**
 * DESIGN §4.1 の `TaskKind`。
 */
export type TaskKind = "plan" | "execute" | "review" | "approval";
/**
 * DESIGN §5.8 の境界。`Remote{cluster, path}` は `[[clusters]] id` と**クラスタ側の**作業ディレクトリ（ADR-0018、Phase 12）。
 * taskd はその写しを `workspace_root/<task_id>` に持ち、コマンドはクラスタで実行する。
 */
export type WorkspaceSpec =
  | {
      kind: "local";
      path: string;
    }
  | {
      cluster: string;
      kind: "remote";
      path: string;
    };
/**
 * run の役割（ADR-0014 D1）。`Event::WorkerStarted` / `WorkerFinished` の `role`。
 */
export type RunRole = "worker" | "reviewer";
export type Action = "approve" | "reject" | "answer" | "cancel";
export type RunOutcomeKind = "done" | "question" | "error" | "requeue" | "lease_expired";
export type AttentionItem =
  | {
      at: string;
      reason: string;
      task: TaskRef;
      type: "failed";
    }
  | {
      at: string;
      count: number;
      max: number;
      task: TaskRef;
      type: "requeue_limit_near";
    }
  | {
      at: string;
      hint: WorkerHint;
      task: TaskRef;
      type: "unroutable";
    }
  | {
      at: string;
      cluster: string;
      host: string;
      tasks: number;
      type: "cluster_unavailable";
    };
/**
 * 受け入れ条件 1 件の指定。現在の `taskctl add` の `--accept`/`--check-cmd`/
 * `--check-artifact`/`--check-reviewer` に対応する。API の `POST /tasks` の `acceptance[]` でもある（`docs/gui/api.md` §3.4）。
 */
export type CriterionSpec =
  | {
      text: string;
      type: "human";
    }
  | {
      cmd: string;
      expect_exit?: number;
      type: "command";
    }
  | {
      name: string;
      type: "artifact_exists";
    }
  | {
      text: string;
      type: "reviewer";
    };

/**
 * スキーマ生成のルート。
 */
export interface ApiV1Schema {
  account: AccountView;
  account_check: AccountCheckResponse;
  account_list: AccountList;
  account_login_result: AccountLoginResult;
  account_login_start: AccountLoginStart;
  answer: AnswerBody;
  artifact_list: ArtifactList;
  cancel: CancelBody;
  clusters: Clusters;
  config: ConfigView;
  daemon: DaemonView;
  decision: DecisionBody;
  events_page: EventsPage;
  graph: Graph;
  health: Health;
  inbox: Inbox;
  new_plan: NewPlanSpec;
  new_task: NewTaskSpec;
  problem: Problem;
  provider_check: ProviderCheckResponse;
  provider_config: ProviderConfigView1;
  providers: Providers;
  reload: ReloadResult;
  replay_report: ReplayReport;
  run_list: RunList;
  stream_daemon: DaemonSnapshot;
  stream_event: EventRow;
  stream_heartbeat: StreamHeartbeat;
  stream_hello: StreamHello;
  stream_reset: StreamReset;
  task: Task;
  task_detail: TaskDetail;
  task_list: TaskList;
  transition_result: TransitionResult;
}
/**
 * 1 アカウント（`GET /accounts` の要素、`POST /accounts` の応答）。
 */
export interface AccountView {
  /**
   * ADR-0025 D1: `"claude-code"` | `"codex"`。
   */
  adapter?: string;
  cooldown?: AccountCooldownView | null;
  /**
   * アカウントディレクトリの絶対パス（ログイン手順に要る。秘密の中身は含まない）。
   */
  dir: string;
  /**
   * `"not_logged_in" | "at_capacity" | "cooldown" | "five_hour_exhausted" | "seven_day_exhausted" | "rejected"`。
   */
  excluded_reason?: string | null;
  id: string;
  /**
   * 実行中の run の数。最初の tick 前は `0`。
   */
  in_use: number;
  last_check?: ProviderCheckView | null;
  /**
   * ログイン済みを示すファイル（claude-code は `.credentials.json`、codex は `auth.json`）の有無
   * （中身は読まない）。
   */
  logged_in: boolean;
  /**
   * ADR-0024 D7: 進行中のログイン中継があるか。
   */
  login_pending: boolean;
  /**
   * ADR-0024 D3 のスコア。除外なら `null`。
   */
  score?: number | null;
  stats: AccountStats;
  usage?: AccountUsageView | null;
}
export interface AccountCooldownView {
  /**
   * `"auth_failed" | "throttled" | "exhausted"`。
   */
  reason: string;
  until: string;
}
/**
 * ADR-0022 D2: 1 回の疎通確認の記録。
 */
export interface ProviderCheckView {
  /**
   * 確認した時刻（RFC 3339）。
   */
  at: string;
  /**
   * 人が読むための一行の手がかり（ワーカーの返答や失敗の理由。ADR-0022 M1）。無ければ `null`。
   */
  detail?: string | null;
  /**
   * `ok` / `auth_failed` / `throttled` / `spawn_failed`（`task_api::ProviderCheckResult` の serde 名）。
   */
  result: string;
}
/**
 * `WorkerStarted.account` / `WorkerFinished` から集計（task-api のメモリ内の観測値。再起動で再計算）。
 */
export interface AccountStats {
  done: number;
  error: number;
  input_tokens: number;
  output_tokens: number;
  runs: number;
}
/**
 * `RateLimitObservation` を RFC 3339 に直したもの。
 */
export interface AccountUsageView {
  five_hour?: RateWindowView | null;
  observed_at: string;
  seven_day?: RateWindowView | null;
  /**
   * `"run" | "check"`。
   */
  source: string;
  status?: string | null;
}
export interface RateWindowView {
  resets_at: string;
  utilization: number;
}
/**
 * `POST /accounts/{id}/check` の応答（ADR-0024 D6）。
 */
export interface AccountCheckResponse {
  checked_at: string;
  detail?: string | null;
  result: ProviderCheckResult;
  usage?: AccountUsageView | null;
}
/**
 * Phase 13（ADR-0024）: Claude アカウントのプール。
 */
export interface AccountList {
  /**
   * `adapter` → `id` の順。
   */
  items: AccountView[];
  max_runs_per_account: number;
  /**
   * `[accounts] claude_dir` の絶対パス。`[accounts]` が無ければ `null`。ADR-0025 D6: `roots["claude-code"]`
   * の別名として残す（後方互換）。
   */
  root?: string | null;
  /**
   * ADR-0025 D6: `"claude-code"` / `"codex"` → 設定されていればその絶対パス、無ければ `null`。
   */
  roots?: {
    [k: string]: string | null;
  };
}
/**
 * `POST /accounts/{id}/login/code` の応答。
 */
export interface AccountLoginResult {
  detail?: string | null;
  /**
   * `"ok" | "failed"`。
   */
  result: string;
}
/**
 * `POST /accounts/{id}/login` の応答（ADR-0024 D7、ADR-0025 D5）。
 */
export interface AccountLoginStart {
  /**
   * claude-code は 10 分後、codex は 15 分後（RFC 3339）。
   */
  expires_at: string;
  /**
   * `"paste_code"`（claude-code: URL を開いて認可し、表示されたコードを `login/code` に貼る）|
   * `"device_code"`（codex: URL を開いて `user_code` を入力する。GUI には貼り戻さない）。
   */
  kind?: string;
  url: string;
  /**
   * codex のみ。`login/code` には使わない（GUI が画面に出すだけ）。ログには出さない。
   */
  user_code?: string | null;
}
/**
 * `POST /tasks/{id}/answer` の本文。
 */
export interface AnswerBody {
  answer: string;
  expected_status?: Status | null;
}
/**
 * `GET /tasks/{id}/artifacts`。
 */
export interface ArtifactList {
  items: ArtifactView[];
}
export interface ArtifactView {
  artifact: ArtifactRef;
  exists: boolean;
  /**
   * パス検査に落ちた（ワークスペース外・symlink 越え・絶対パス等）。本体の取得は 403。
   */
  forbidden: boolean;
  /**
   * `ArtifactProduced` の出現順（0 始まり）。`GET /tasks/{id}/artifacts/{idx}` の添字。
   */
  idx: number;
  run_id: string;
  /**
   * 64 MiB 以下のときだけ計算する。
   */
  sha256_current?: string | null;
  /**
   * 記録値との一致。`exists = false` または未計算なら `null`。
   */
  sha256_matches?: boolean | null;
  size?: number | null;
  ts: string;
}
/**
 * DESIGN §4.4 の `ArtifactRef`。実体は `workspace/<task_id>/artifacts/` 配下。
 */
export interface ArtifactRef {
  kind: string;
  name: string;
  path: string;
  sha256: string;
}
/**
 * `POST /tasks/{id}/cancel` の本文。
 */
export interface CancelBody {
  expected_status?: Status | null;
}
/**
 * `GET /clusters`（ADR-0018 受け入れ条件8）。
 */
export interface Clusters {
  items: ClusterView[];
}
/**
 * 設定（`[[clusters]]`）とスナップショット（`ClusterLive`）を結合したもの。`env` の値は出さない。
 */
export interface ClusterView {
  concurrency: number;
  /**
   * この tick で `ssh -O check` が成功したか。スナップショットが無ければ `null`。
   */
  connected?: boolean | null;
  /**
   * `cooldown_until − now`（秒）。過ぎていれば両方 `null`。
   */
  cooldown_remaining_secs?: number | null;
  /**
   * cooldown 中ならその終わり（RFC 3339）。
   */
  cooldown_until?: string | null;
  delete_on_push: boolean;
  /**
   * `env` のキー名だけ（昇順）。
   */
  env_keys: string[];
  /**
   * `setup` が 1 行以上あるか（中身は出さない）。
   */
  has_setup: boolean;
  /**
   * `~/.ssh/config` の `Host` 名。
   */
  host: string;
  id: string;
  /**
   * スナップショットが無ければ `null`。
   */
  in_use?: number | null;
  rsync_excludes: string[];
  /**
   * `"rsync"` | `"none"`。
   */
  sync: string;
}
/**
 * `GET /config`: `taskd.toml` の要約。env の値・トークンは含めない。taskd が起動時に作る。
 */
export interface ConfigView {
  api: ApiConfigView;
  /**
   * ADR-0018: `[[clusters]]` の要約（`env` はキー名だけ、`setup` は有無だけ）。
   */
  clusters?: ClusterConfigView[];
  config_path: string;
  /**
   * DB の絶対パス。
   */
  db: string;
  delegation?: DelegationLimits;
  error_cooldown_secs: number;
  idle_timeout_secs: number;
  kill_grace_secs: number;
  lease_grace_secs: number;
  max_concurrency: number;
  max_requeues: number;
  plan_auto_accept: boolean;
  providers: ProviderConfigView[];
  retry_backoff_base_secs: number;
  retry_backoff_max_secs: number;
  review_timeout_secs: number;
  reviewer: ReviewerConfigView;
  /**
   * ADR-0016 D1: `[[roles]]` の要約（指示文の本文は出さない）。
   */
  roles?: RoleConfigView[];
  tick_ms: number;
  workspace_root: string;
}
export interface ApiConfigView {
  allowed_hosts: string[];
  auth_required: boolean;
  bind: string;
}
/**
 * `[[clusters]]` 1 行の要約（ADR-0018 D7: `env` の値は出さない）。
 */
export interface ClusterConfigView {
  concurrency: number;
  delete_on_push: boolean;
  /**
   * `env` のキー名だけ（昇順）。
   */
  env_keys: string[];
  /**
   * `setup` が 1 行以上あるか（中身は出さない）。
   */
  has_setup: boolean;
  /**
   * `~/.ssh/config` の `Host` 名。
   */
  host: string;
  id: string;
  rsync_excludes: string[];
  /**
   * `"rsync"` | `"none"`。
   */
  sync: string;
}
/**
 * ADR-0016 D2: `[delegation]` の上限。
 */
export interface DelegationLimits {
  /**
   * 1 run あたりの件数（複数の `delegate` をまたいで数える）。
   */
  max_delegate_per_run: number;
  /**
   * 木の深さ（根 = 1）。
   */
  max_tree_depth: number;
  /**
   * 木全体のワーカー run 数。
   */
  max_tree_runs: number;
  /**
   * ADR-0021 D4: 委譲した子が失敗したときの親の扱い。
   */
  on_child_failure: "retry_then_ask" | "ignore";
}
export interface ProviderConfigView {
  /**
   * ADR-0024 D2: `[accounts]` のプールから選ぶか（既定 `false`）。
   */
  account_pool?: boolean;
  adapter: string;
  concurrency: number;
  /**
   * `[[providers]].env` のキー名だけ。
   */
  env_keys: string[];
  id: string;
  /**
   * 実効モデル（空なら `null`）。
   */
  model?: string | null;
  tiers: Tier[];
}
export interface ReviewerConfigView {
  adapter?: string | null;
  tier: Tier;
}
/**
 * `[[roles]]` 1 行の要約（ADR-0016 D1）。`instructions` は**本文を出さない**（プロンプトの中身は設定ファイルにだけ置く）。
 */
export interface RoleConfigView {
  adapter?: string | null;
  /**
   * 指示文が 1 文字以上あるか（中身は出さない）。
   */
  has_instructions: boolean;
  id: string;
  max_turns?: number | null;
  max_wall_secs?: number | null;
  tier?: Tier | null;
}
/**
 * `GET /daemon`。
 */
export interface DaemonView {
  now: string;
  /**
   * 最初の tick より前は `null`。
   */
  snapshot?: DaemonSnapshot | null;
}
export interface DaemonSnapshot {
  /**
   * ADR-0024/0025: プールのアカウント（`adapter` → `id` の順、id 昇順）。`[accounts]` が無ければ空。
   */
  accounts?: AccountLive[];
  /**
   * ADR-0024 D1/D5: `[accounts] claude_dir` の絶対パス（`[accounts]` が無ければ `None`）。
   * ADR-0025 D6: claude-code の根の別名として残す（`accounts_roots["claude-code"]` と同じ値）。
   */
  accounts_root?: string | null;
  /**
   * ADR-0025 D1/D6: アダプタごとの根ディレクトリ（`"claude-code"` / `"codex"` → 絶対パス。設定されていない
   * アダプタはキーごと無い）。古いスナップショットには無いので既定は空。
   */
  accounts_roots?: {
    [k: string]: string;
  };
  /**
   * ADR-0023 D3: 委譲した子が終わるのを待っている親（`reviewing` のまま。id 昇順）。
   * 「自分の判定待ち」と区別するための観測値。古いスナップショットには無いので既定は空。
   */
  awaiting_children?: TaskId[];
  /**
   * 人間の承認待ちでレビューを延期している reviewing タスク。
   */
  awaiting_human: TaskId[];
  /**
   * ADR-0018: `[[clusters]]` の稼働状況（`id` 昇順）。第 2 段階で追加したので、古いスナップショットには無い。
   */
  clusters?: ClusterLive[];
  cooldowns: CooldownView[];
  hostname: string;
  in_flight: InFlight[];
  /**
   * 起動ごとの ULID（`GET /health` の `instance_id` と同じ）。
   */
  instance_id: string;
  last_tick_at: string;
  /**
   * ADR-0024 D1: `[accounts] max_runs_per_account`（`[accounts]` が無ければ `None`）。
   */
  max_runs_per_account?: number | null;
  pid: number;
  providers: ProviderLive[];
  started_at: string;
  tick_ms: number;
  ticks: number;
  /**
   * 設定に合うプロバイダが無い ready タスク（この tick の判定）。
   */
  unroutable: TaskId[];
}
/**
 * ADR-0024/0025: プールの 1 アカウントの稼働状況（観測値。DB には書かない）。
 */
export interface AccountLive {
  /**
   * ADR-0025 D1: `"claude-code"` | `"codex"`。古いスナップショットには無いので既定は `"claude-code"`。
   */
  adapter?: string;
  cooldown?: AccountCooldownLive | null;
  /**
   * `"not_logged_in" | "at_capacity" | "cooldown" | "five_hour_exhausted" | "seven_day_exhausted" | "rejected"`。
   */
  excluded_reason?: string | null;
  id: string;
  /**
   * 実行中の run（ワーカー run + このアカウントを使う Reviewer run）の数。
   */
  in_use: number;
  last_check?: ProviderCheckView | null;
  /**
   * ログイン済みを示すファイル（claude-code は `.credentials.json`、codex は `auth.json`）の有無。
   */
  logged_in: boolean;
  /**
   * 進行中のログイン中継（ADR-0024 D7）があるか。
   */
  login_pending?: boolean;
  /**
   * ADR-0024 D3 のスコア。除外されていれば `None`。
   */
  score?: number | null;
  usage?: AccountUsageLive | null;
}
/**
 * アカウントの cooldown（Unix 秒）。
 */
export interface AccountCooldownLive {
  /**
   * `"auth_failed" | "throttled" | "exhausted"`。
   */
  reason: string;
  until: number;
}
/**
 * `RateLimitObservation` の観測値部分（Unix 秒のまま。壁時計の文字列化は task-api が行う）。
 */
export interface AccountUsageLive {
  five_hour?: RateWindow | null;
  observed_at: number;
  seven_day?: RateWindow | null;
  /**
   * `"run" | "check"`。
   */
  source: string;
  status?: string | null;
}
/**
 * 1 つの枠（5 時間 / 7 日）の観測値。
 */
export interface RateWindow {
  /**
   * 枠がリセットされる時刻（Unix 秒、`resetsAt`）
   */
  resets_at: number;
  /**
   * 0.0〜1.0（`unifiedWindows.<w>.utilization`）
   */
  utilization: number;
}
/**
 * クラスタ（`[[clusters]]` の行）の稼働状況（ADR-0018 D2 / D5）。`env` の値・`setup` の中身は含めない。
 */
export interface ClusterLive {
  concurrency: number;
  /**
   * この tick で `ssh -O check` が成功した（人が張った多重接続がある）。
   */
  connected: boolean;
  /**
   * 多重接続が無くて cooldown 中なら、その終わり（RFC 3339）。
   */
  cooldown_until?: string | null;
  /**
   * `~/.ssh/config` の `Host` 名。
   */
  host: string;
  id: string;
  /**
   * このクラスタで走っている run（ワーカー run + 判定）の数。
   */
  in_use: number;
}
/**
 * `task_dispatch::policy::Cooldown`（`Instant`）を壁時計に直したもの。
 */
export interface CooldownView {
  provider: string;
  /**
   * `"throttled" | "auth_failed" | "exhausted"`。
   */
  reason: string;
  until: string;
}
/**
 * 実行中の run（ワーカー run、またはプロバイダを使う Reviewer run）。
 */
export interface InFlight {
  kind: InFlightKind;
  provider: string;
  run_id: string;
  since: string;
  task_id: TaskId;
}
/**
 * プロバイダ（`[[providers]]` の行 = アカウント）の稼働状況。`env` の値は含めない。
 */
export interface ProviderLive {
  /**
   * ADR-0024 D2: `[accounts]` のプールから選ぶか。古いスナップショットには無いので既定 `false`。
   */
  account_pool?: boolean;
  adapter: string;
  concurrency: number;
  /**
   * `env` のキー名だけ（値は出さない）。古いスナップショットには無いので既定は空（ADR-0017 M4）。
   */
  env_keys?: string[];
  id: string;
  /**
   * 実行中の run と Reviewer run の合計。
   */
  in_use: number;
  /**
   * ADR-0022 D2: 直近の疎通確認（`POST /providers/{id}/check`）の結果。**メモリだけに持つ観測値**で、
   * taskd を再起動すると消える（イベントにも DB にも残さない）。一度も確認していなければ `None`。
   */
  last_check?: ProviderCheckView | null;
  /**
   * 実効モデル（空なら `None`）。
   */
  model?: string | null;
  tiers: Tier[];
}
/**
 * `POST /tasks/{id}/approve`、`POST /tasks/{id}/reject` の本文。
 */
export interface DecisionBody {
  expected_status?: Status | null;
  note?: string | null;
}
/**
 * `GET /tasks/{id}/events`、`GET /events`。
 */
export interface EventsPage {
  has_more: boolean;
  items: EventRow[];
}
/**
 * `events` テーブルの 1 行（ADR-0013 D6）。`id` はテーブル全体でのグローバル単調増加値。
 */
export interface EventRow {
  event: Event;
  id: number;
  seq: number;
  task_id: TaskId;
  /**
   * DB に保存された RFC 3339 文字列そのまま。
   */
  ts: string;
}
/**
 * DESIGN §4.1 の `Task`。
 */
export interface Task {
  acceptance: Criterion[];
  /**
   * ADR-0016 D3: true なら、委譲した子が全て終端になった後に集約 run を 1 回だけ行い `artifacts/summary.md` を作らせる。
   */
  aggregate?: boolean;
  attempts: number;
  budget: Budget;
  created_at: string;
  depends_on: TaskId[];
  id: TaskId;
  inputs: ArtifactRef[];
  kind: TaskKind;
  lease?: Lease | null;
  objective: string;
  parent_id?: TaskId | null;
  priority: number;
  /**
   * ADR-0016 D1: 役割名（自由記述。`[[roles]] id` と一致すれば既定と指示文が効く）。状態機械は見ない。
   * 導入前のタスクには無いので任意。
   */
  role?: string | null;
  status: Status;
  title: string;
  updated_at: string;
  worker_hint: WorkerHint;
  workspace: WorkspaceSpec;
}
/**
 * DESIGN §4.1 の `Criterion`。
 */
export interface Criterion {
  check: Check;
  text: string;
}
/**
 * DESIGN §4.1 の `Budget`。
 */
export interface Budget {
  max_retries: number;
  max_turns: number;
  max_wall_secs: number;
}
/**
 * DESIGN §4.1 の `Lease`。ADR-0002 D7: `expires_at` は
 * `budget.max_wall_secs + 猶予` から `acquire_lease` 呼び出し側が計算する。
 */
export interface Lease {
  expires_at: string;
  worker_run_id: string;
}
export interface WorkerHint {
  adapter?: string | null;
  tier: Tier;
}
/**
 * DESIGN §5.3 の `usage`。取れない項目は省略可。
 */
export interface Usage {
  input_tokens?: number | null;
  output_tokens?: number | null;
}
export interface Graph {
  edges: GraphEdge[];
  nodes: GraphNode[];
}
export interface GraphEdge {
  /**
   * タスクの一意識別子（ULID）。DESIGN §4.1。
   */
  from: string;
  /**
   * 常に `"depends_on"`。
   */
  kind: string;
  /**
   * タスクの一意識別子（ULID）。DESIGN §4.1。
   */
  to: string;
}
export interface GraphNode {
  id: TaskId;
  kind: TaskKind;
  parent_id?: TaskId | null;
  /**
   * ADR-0016 D1 の `Task.role`（GUI-R2: DAG のノードに役割のラベルを出すため）。
   */
  role?: string | null;
  status: Status;
  title: string;
}
/**
 * `GET /health`（無認証）。
 */
export interface Health {
  /**
   * 常に `"1"`。
   */
  api_version: string;
  db: DbInfo;
  instance_id: string;
  now: string;
  /**
   * `schema_migrations` の最大版数。
   */
  schema_version: number;
  started_at: string;
  taskd_version: string;
}
export interface DbInfo {
  busy_timeout_ms: number;
  /**
   * `PRAGMA journal_mode` の実測値（`"wal"` でなければ設定不備）。
   */
  journal_mode: string;
}
export interface Inbox {
  approvals: ApprovalItem[];
  attention: AttentionItem[];
  counts: InboxCounts;
  drafts: DraftGroup[];
  questions: QuestionItem[];
}
export interface ApprovalItem {
  approval: TaskRef;
  artifacts: ArtifactRef[];
  attempt?: number | null;
  criterion_idx?: number | null;
  criterion_text: string;
  evidence: EvidenceView[];
  last_run?: RunSummary | null;
  other_verdicts: VerdictView[];
  parent?: TaskRef | null;
  previous_decisions: ApprovalDecisionView[];
  requested_at: string;
}
export interface TaskRef {
  /**
   * 今この状態で許される操作（ADR-0015 D4。GUI は §5.4 の規則を再実装しない）。
   */
  actions: Action[];
  id: TaskId;
  kind: TaskKind;
  status: Status;
  title: string;
}
/**
 * `task_worker::Evidence` と同じ形。
 */
export interface EvidenceView {
  command?: string | null;
  criterion: number;
  exit?: number | null;
  stdout_tail?: string | null;
}
export interface RunSummary {
  /**
   * プールのアカウント（ADR-0024 D4 / ADR-0025）。`WorkerStarted.account` がある run だけ。
   */
  account?: string | null;
  adapter: string;
  artifacts: number;
  /**
   * `runs/<run_id>/` のファイルの有無。task-ops は `None` を入れ、task-api が埋める。
   */
  files?: RunFiles | null;
  finished_at?: string | null;
  model: string;
  outcome?: RunOutcomeKind | null;
  outcome_text?: string | null;
  progress: number;
  provider?: string | null;
  reviewer_deferrals: number;
  /**
   * ワーカー run か Reviewer run か（ADR-0014 D1。イベントに `role` が無ければ `worker`）。
   */
  role: "worker" | "reviewer";
  run_id: string;
  started_at: string;
  usage?: Usage | null;
  verdicts: number;
}
export interface RunFiles {
  /**
   * ADR-0023 M1: `runs/<run_id>/prompt.txt`（claude-code / codex が実際に渡した文面）。fake には無い。
   */
  prompt?: boolean;
  /**
   * ADR-0023 D2: `runs/<run_id>/request.json`（ワーカーに渡した指示）。導入前の run には無いので既定は false。
   */
  request?: boolean;
  result: boolean;
  stderr: boolean;
  stdout: boolean;
}
export interface VerdictView {
  criterion_idx: number;
  pass: boolean;
  reason: string;
  run_id: string;
  ts: string;
}
export interface ApprovalDecisionView {
  approved: boolean;
  by: string;
  note?: string | null;
  ts: string;
}
export interface InboxCounts {
  approvals: number;
  attention: number;
  /**
   * status 名 → 件数（DB 全体）。
   */
  by_status: {
    [k: string]: number;
  };
  drafts: number;
  questions: number;
}
export interface DraftGroup {
  drafts: TaskSummary[];
  parent?: TaskRef | null;
  plan_summary?: string | null;
}
export interface TaskSummary {
  /**
   * 今この状態で許される操作（ADR-0015 D4）。
   */
  actions: Action[];
  adapter?: string | null;
  attempts: number;
  backoff_until?: string | null;
  children: number;
  created_at: string;
  depends_on: TaskId[];
  id: TaskId;
  kind: TaskKind;
  lease_expires_at?: string | null;
  max_retries: number;
  parent_id?: TaskId | null;
  pending_children: number;
  priority: number;
  /**
   * ADR-0016 D1 の `Task.role`（GUI-R2: 一覧の各行に役割のラベルを出すため。`TaskDetail.role` と同じ値）。
   */
  role?: string | null;
  status: Status;
  tier: Tier;
  title: string;
  updated_at: string;
}
export interface QuestionItem {
  asked_at?: string | null;
  previous: AnswerNote[];
  question: string;
  run_id?: string | null;
  task: TaskRef;
}
/**
 * `answers_from_events` の要素。`task_worker::Answer` と同じ形（フィールド名も同じ）。
 */
export interface AnswerNote {
  answer: string;
  question: string;
}
/**
 * `taskctl plan` から組み立てる新規 Plan タスクの指定。API の `POST /plans` の本文でもある（`docs/gui/api.md` §3.14）。
 */
export interface NewPlanSpec {
  /**
   * 大目標。1行目の先頭80文字が `title` になる。
   */
  goal: string;
  max_retries?: number;
  max_turns?: number;
  max_wall_secs?: number;
  priority?: number;
  /**
   * DESIGN §5.4 の `WorkerHint`。
   */
  tier?: "frontier" | "standard" | "cheap";
  workspace?: string | null;
}
/**
 * `taskctl add` から組み立てる新規タスクの指定。API の `POST /tasks` の本文でもある（`docs/gui/api.md` §3.4）。
 * 省略時の既定は `taskctl add` と同じ。
 */
export interface NewTaskSpec {
  acceptance: CriterionSpec[];
  /**
   * 省略時は役割の既定 → 指定なし。
   */
  adapter?: string | null;
  /**
   * ADR-0016 D3: 委譲した子が全て終端になった後に集約 run を 1 回行う。
   */
  aggregate?: boolean;
  /**
   * ADR-0018: 指定すると `WorkspaceSpec::Remote{cluster, path}` になり、コマンドはそのクラスタで実行される。
   * `workspace` がクラスタ側の作業ディレクトリ（既存プロジェクトでよい）。
   */
  cluster?: string | null;
  depends_on?: TaskId[];
  /**
   * DESIGN §4.1 の `TaskKind`。
   */
  kind?: "plan" | "execute" | "review" | "approval";
  max_retries?: number;
  /**
   * 省略時は役割の既定 → 10。
   */
  max_turns?: number | null;
  /**
   * 省略時は役割の既定 → 600。
   */
  max_wall_secs?: number | null;
  objective: string;
  parent?: TaskId | null;
  priority?: number;
  /**
   * ADR-0016 D1: 役割名（自由記述）。`[[roles]]` にあれば省略値の既定と run 時の指示文が効く。
   */
  role?: string | null;
  /**
   * 省略時は役割の既定 → `standard`（ADR-0016 D1 / M3: タスクの値 > 役割の既定 > 全体の既定）。
   */
  tier?: Tier | null;
  title: string;
  workspace?: string | null;
}
/**
 * RFC 9457 の problem details（`application/problem+json`）。`extra` は `code` ごとの付加フィールド。
 */
export interface Problem {
  code: string;
  detail: string;
  /**
   * `urn:taskd:request:<X-Request-Id>`。
   */
  instance: string;
  status: number;
  title: string;
  /**
   * `urn:taskd:problem:<code>`。
   */
  type: string;
  [k: string]: unknown;
}
/**
 * `POST /api/v1/providers/{id}/check` の応答（ADR-0017 D2）。
 */
export interface ProviderCheckResponse {
  checked_at: string;
  /**
   * ADR-0022 M1: 人が読むための一行の手がかり（ワーカーの返答、失敗の理由）。無ければ `null`。
   */
  detail?: string | null;
  result: ProviderCheckResult;
}
/**
 * `POST /api/v1/providers` と `PATCH /api/v1/providers/{id}` の応答（ADR-0017）。
 */
export interface ProviderConfigView1 {
  /**
   * ADR-0024 D2: `[accounts]` のプールから選ぶか（既定 `false`）。
   */
  account_pool?: boolean;
  adapter: string;
  concurrency: number;
  /**
   * `[[providers]].env` のキー名だけ。
   */
  env_keys: string[];
  id: string;
  /**
   * 実効モデル（空なら `null`）。
   */
  model?: string | null;
  tiers: Tier[];
}
/**
 * `GET /providers`。
 */
export interface Providers {
  items: ProviderView[];
}
export interface ProviderView {
  /**
   * ADR-0024 D2: `[accounts]` のプールから選ぶか（既定 `false`）。
   */
  account_pool?: boolean;
  adapter: string;
  concurrency: number;
  /**
   * スナップショットが無い、または cooldown 中でなければ `null`。
   */
  cooldown?: CooldownView | null;
  /**
   * `env` のキー名だけ（値は出さない）。
   */
  env_keys: string[];
  id: string;
  /**
   * スナップショットが無ければ `null`。
   */
  in_use?: number | null;
  /**
   * ADR-0022 D2: 直近の `POST /providers/{id}/check` の結果（`{at, result}`）。まだ確認していない、
   * または taskd を再起動した後は `null`（メモリだけに持つ観測値）。
   */
  last_check?: ProviderCheckView | null;
  model?: string | null;
  stats: ProviderStats;
  tiers: Tier[];
}
/**
 * プロバイダ別の run 集計（task-api のメモリ内の観測値。再起動で再計算）。
 */
export interface ProviderStats {
  /**
   * `WorkerFinished.ts` の UTC 日付で直近 30 日（昇順。run の無い日は現れない）。
   */
  by_day: DailyUsage[];
  done: number;
  error: number;
  input_tokens: number;
  lease_expired: number;
  output_tokens: number;
  question: number;
  requeue: number;
  /**
   * `WorkerStarted` の数（実行中を含む）。
   */
  runs: number;
}
export interface DailyUsage {
  /**
   * `YYYY-MM-DD`（UTC）。
   */
  day: string;
  input_tokens: number;
  output_tokens: number;
  /**
   * その日に終わった run の数。
   */
  runs: number;
}
/**
 * `POST /api/v1/reload` の応答（ADR-0017 D1）。
 */
export interface ReloadResult {
  reloaded: boolean;
}
/**
 * `replay` の結果。
 */
export interface ReplayReport {
  mismatches: ReplayMismatch[];
  tasks: number;
}
/**
 * `replay` が検出した 1 件の食い違い。
 */
export interface ReplayMismatch {
  /**
   * `"status"` または `"attempts"`。
   */
  field: string;
  /**
   * `events` から再構築した値。
   */
  replayed: string;
  /**
   * `tasks` テーブルに保存されている値。
   */
  stored: string;
  task_id: TaskId;
}
/**
 * `GET /tasks/{id}/runs`。
 */
export interface RunList {
  runs: RunSummary[];
}
/**
 * SSE `event: heartbeat`。
 */
export interface StreamHeartbeat {
  now: string;
}
/**
 * SSE `event: hello`。
 */
export interface StreamHello {
  /**
   * 送信開始位置（この id より後の `task.event` を送る）。
   */
  cursor: number;
  daemon?: DaemonSnapshot | null;
  now: string;
}
/**
 * SSE `event: reset`。クライアントは全体を再取得する。
 */
export interface StreamReset {
  /**
   * 以後の送信開始位置（最新の id）。
   */
  cursor: number;
  /**
   * `"cursor_too_old"` | `"cursor_ahead"`。
   */
  reason: string;
}
/**
 * `taskctl show --json` と `GET /api/v1/tasks/{id}` の本体。
 */
export interface TaskDetail {
  actions: Action[];
  answers: AnswerNote[];
  approvals: ApprovalLink[];
  children: TaskRef[];
  /**
   * ADR-0018: `WorkspaceSpec::Remote` のクラスタ（`[[clusters]] id`）。ローカルのタスクは `null`。
   */
  cluster?: string | null;
  criteria: CriterionView[];
  /**
   * ADR-0016 D2: 各 run が `delegate` で作った子（`Event::Delegated` の順）。
   */
  delegated: DelegatedView[];
  dependencies: TaskRef[];
  dependents: TaskRef[];
  latest_question?: string | null;
  prior_review: ReviewNote[];
  /**
   * ADR-0016 D1: `Task.role`（GUI の表示用に最上位にも出す）。
   */
  role?: string | null;
  runs: RunSummary[];
  task: Task;
  timers: Timers;
  worker_run_hint?: string | null;
  /**
   * 手元の作業ディレクトリ（絶対パス）。`WorkspaceSpec::Remote` では写し `workspace_root/<task_id>`（run のログはここ。ADR-0018 D1）。
   */
  workspace_dir?: string | null;
  /**
   * ADR-0019 D2: `sync = "worktree"` のクラスタで動くタスクの worktree。人はここを見て diff / commit する。
   */
  worktree?: WorktreeView | null;
}
export interface ApprovalLink {
  approval: TaskRef;
  attempt?: number | null;
  criterion_idx?: number | null;
  decided?: ApprovalDecisionView | null;
}
export interface CriterionView {
  approval?: ApprovalLink | null;
  check: Check;
  idx: number;
  latest_verdict?: VerdictView | null;
  text: string;
}
/**
 * ADR-0016 D2: 1 回の `delegate`（`Event::Delegated`）の要約。
 */
export interface DelegatedView {
  run_id: string;
  /**
   * 子の現在の状態。既に存在しない ID は落とす。
   */
  tasks: TaskRef[];
  /**
   * イベントの ts（`EventRow.ts`）。
   */
  ts: string;
}
/**
 * `prior_review_from_events` の要素。`task_worker::PriorReview` と同じ形（フィールド名も同じ）。
 */
export interface ReviewNote {
  criterion: number;
  pass: boolean;
  reason: string;
}
export interface Timers {
  backoff_until?: string | null;
  consecutive_requeues: number;
  consecutive_reviewer_requeues: number;
  lease_expires_at?: string | null;
  max_requeues: number;
  now: string;
}
/**
 * ADR-0019 D2: クラスタ側の worktree（taskd はここだけを触り、commit はしない）。
 */
export interface WorktreeView {
  /**
   * worktree のブランチ（`taskd/<task_id>`）。taskd は commit しないので、変更は作業ツリーに残る。
   */
  branch: string;
  /**
   * worktree のパス（クラスタ上）。
   */
  dir: string;
  /**
   * 元のリポジトリ（`WorkspaceSpec::Remote.path`）。
   */
  project: string;
}
export interface TaskList {
  /**
   * status 名 → 件数（フィルタに関係なく DB 全体。0 件の status は現れない）。
   */
  counts_by_status: {
    [k: string]: number;
  };
  items: TaskSummary[];
  next_cursor?: string | null;
  total: number;
}
/**
 * 状態変更の結果（承認・却下・回答・取り消し共通）。
 */
export interface TransitionResult {
  /**
   * この遷移の伝播で `cancelled` になった、対象タスク以外のタスク（`docs/gui/api.md` §5.7）。
   */
  cascaded?: TaskRef[];
  from: Status;
  id: TaskId;
  reason: string;
  to: Status;
}
