/* eslint-disable */
/**
 * Generated by `pnpm gen:types` from taskd's docs/api/v1/api-v1.schema.json (taskd HTTP API v1).
 * DO NOT EDIT. Re-run `pnpm gen:types` after taskd updates the schema.
 */

/**
 * `POST /api/v1/providers/{id}/check` の結果（ADR-0017 D2）。
 */
export type ProviderCheckResult = "ok" | "auth_failed" | "throttled" | "spawn_failed";
/**
 * ADR-0002 D1 の状態集合。終端は `done | failed | cancelled`。
 */
export type Status = "draft" | "ready" | "running" | "blocked" | "reviewing" | "done" | "failed" | "cancelled";
/**
 * 人の決定（SPEC §3.6）。
 */
export type Decision = "once" | "standing" | "denied";
/**
 * 認可 1 件の識別子（ULID）。
 */
export type ApprovalId = string;
/**
 * 案件の一意識別子（ULID）。`TaskId` と同じ形。
 */
export type ProjectId = string;
/**
 * タスクの一意識別子（ULID）。DESIGN §4.1。
 */
export type TaskId = string;
/**
 * 永続の規則の識別子（ULID）。
 */
export type StandingRuleId = string;
export type Action = "approve" | "reject" | "answer" | "cancel";
/**
 * DESIGN §4.1 の `TaskKind`。
 */
export type TaskKind = "plan" | "execute" | "review" | "approval";
/**
 * DESIGN §5.4 の `WorkerHint`。
 */
export type Tier = "frontier" | "standard" | "cheap";
export type InFlightKind = "worker" | "reviewer";
/**
 * DESIGN §4.3 の `Event`（追記専用）。ADR-0002 D2: `Transitioned` は遷移の
 * *結果* を記録するものであり、`transition()` の入力（`Trigger`）とは別物。
 * `JsonSchema` は ADR-0013 D8: `docs/api/v1/event.schema.json`（`EventRow` 経由）の契約に使う。
 */
export type Event =
  | {
      task: Task;
      type: "created";
    }
  | {
      from: Status;
      reason: string;
      to: Status;
      type: "transitioned";
    }
  | {
      /**
       * プール（`account_pool = true`）で選ばれた Claude アカウントの id（ADR-0024 D4）。プールを使わない
       * プロバイダ・導入前のイベントには無い。`provider`（アダプタ×プロバイダ行）とは別軸。
       */
      account?: string | null;
      adapter: string;
      model: string;
      /**
       * どのプロバイダ（= アカウント）で実行したか（ADR-0012 D1）。導入前のイベントには無いので任意。
       */
      provider?: string | null;
      /**
       * ADR-0014 D1: `None` はワーカー run、`Some(Reviewer)` は Reviewer run（ワーカー run に `Some(Worker)` は書かない）。
       */
      role?: RunRole | null;
      run_id: string;
      /**
       * ADR-0016 D1: run 開始時のタスクの役割名（`Task.role`）。役割の無いタスク・導入前のイベントには無い。
       */
      task_role?: string | null;
      type: "worker_started";
    }
  | {
      msg: string;
      run_id: string;
      type: "worker_progress";
    }
  | {
      artifact: ArtifactRef;
      run_id: string;
      type: "artifact_produced";
    }
  | {
      outcome: string;
      /**
       * ADR-0014 D1: `WorkerStarted.role` と同じ（`None` はワーカー run）。
       */
      role?: RunRole | null;
      run_id: string;
      type: "worker_finished";
      usage?: Usage | null;
    }
  | {
      criterion_idx: number;
      pass: boolean;
      reason: string;
      run_id: string;
      type: "review_verdict";
    }
  | {
      type: "approval_requested";
    }
  | {
      approved: boolean;
      by: string;
      note?: string | null;
      type: "approval_decided";
    }
  | {
      answer: string;
      question: string;
      type: "answered";
    }
  | {
      /**
       * この質問のきっかけになった run（親の直近の run）。
       */
      run_id: string;
      text: string;
      type: "question_raised";
    }
  | {
      run_id: string;
      task_ids: TaskId[];
      type: "delegated";
    }
  | {
      cluster: string;
      /**
       * `~/.ssh/config` の `Host` 名（`scripts/cluster-login.sh <host>` を案内するため）。第 1 段階の行には無いので任意。
       */
      host?: string;
      reason: string;
      type: "cluster_unavailable";
    }
  | {
      provider: string;
      /**
       * 供給側失敗の種別（ADR-0013 D9）: `throttled | auth_failed | exhausted | spawn`。
       * 導入前のイベントには無いので任意。このバリアントを構築している箇所は現状無い
       * （`grep -rn ProviderThrottled crates` で確認済み）。
       */
      reason?: string | null;
      type: "provider_throttled";
      until: string;
    };
/**
 * DESIGN §5.3/§5.7 の `Check` 種別。
 */
export type Check =
  | {
      cmd: string;
      expect_exit: number;
      type: "command";
    }
  | {
      name: string;
      type: "artifact_exists";
    }
  | {
      type: "reviewer";
    }
  | {
      type: "human";
    };
/**
 * 対話の 1 行の識別子（ULID）。
 */
export type MessageId = string;
/**
 * 途中目標の一意識別子（ULID）。
 */
export type MilestoneId = string;
/**
 * DESIGN §5.8 の境界。`Remote{cluster, path}` は `[[clusters]] id` と**クラスタ側の**作業ディレクトリ（ADR-0018、Phase 12）。
 * taskd はその写しを `workspace_root/<task_id>` に持ち、コマンドはクラスタで実行する。
 */
export type WorkspaceSpec =
  | {
      kind: "local";
      path: string;
    }
  | {
      cluster: string;
      kind: "remote";
      path: string;
    };
/**
 * run の役割（ADR-0014 D1）。`Event::WorkerStarted` / `WorkerFinished` の `role`。
 */
export type RunRole = "worker" | "reviewer";
export type RunOutcomeKind = "done" | "question" | "error" | "requeue" | "lease_expired";
export type AttentionItem =
  | {
      at: string;
      reason: string;
      task: TaskRef;
      type: "failed";
    }
  | {
      at: string;
      count: number;
      max: number;
      task: TaskRef;
      type: "requeue_limit_near";
    }
  | {
      at: string;
      hint: WorkerHint;
      task: TaskRef;
      type: "unroutable";
    }
  | {
      at: string;
      cluster: string;
      host: string;
      tasks: number;
      type: "cluster_unavailable";
    };
/**
 * 誰が言ったか（ADR-0033 D4）。`user` = 人、`node` = 組織のノード（その run の返事）。
 */
export type MessageRole = "user" | "node";
/**
 * 途中目標の状態（ADR-0033 D2。SPEC §7 のアジャイル: 達成ごとに人が判定し、Go か再設計）。
 */
export type MilestoneStatus = "proposed" | "approved" | "in_progress" | "reached" | "redesigned";
/**
 * 受け入れ条件 1 件の指定。現在の `taskctl add` の `--accept`/`--check-cmd`/
 * `--check-artifact`/`--check-reviewer` に対応する。API の `POST /tasks` の `acceptance[]` でもある（`docs/gui/api.md` §3.4）。
 */
export type CriterionSpec =
  | {
      text: string;
      type: "human";
    }
  | {
      cmd: string;
      expect_exit?: number;
      type: "command";
    }
  | {
      name: string;
      type: "artifact_exists";
    }
  | {
      text: string;
      type: "reviewer";
    };
/**
 * 組織のノードの種類（ADR-0033 D1）。`secretary` は根で 1 つだけ。
 */
export type OrgKind = "secretary" | "department" | "section";
/**
 * 案件の状態（ADR-0033 D2）。
 */
export type ProjectStatus = ("active" | "paused" | "done") | "proposed";
/**
 * 報告の一意識別子（ULID）。
 */
export type ReportId = string;
/**
 * 報告の種類（ADR-0033 D3）。
 */
export type ReportKind = "progress" | "result" | "bad_news" | "proposal" | "question";

/**
 * スキーマ生成のルート。
 */
export interface ApiV1Schema {
  account: AccountView;
  account_check: AccountCheckResponse;
  account_list: AccountList;
  account_login_result: AccountLoginResult;
  account_login_start: AccountLoginStart;
  answer: AnswerBody;
  approval_decide: ApprovalDecideBody;
  approval_decide_result: ApprovalDecideResult;
  approval_list: ApprovalList;
  artifact_list: ArtifactList;
  cancel: CancelBody;
  cluster_connect_result: ClusterConnectResult;
  cluster_connect_start: ClusterConnectStart;
  clusters: Clusters;
  config: ConfigView;
  daemon: DaemonView;
  decision: DecisionBody;
  events_page: EventsPage;
  graph: Graph;
  health: Health;
  inbox: Inbox;
  memory: MemoryView;
  message_accepted: MessageAccepted;
  message_list: MessageList;
  message_post: MessagePostBody;
  milestone_create: MilestoneCreateBody;
  milestone_patch: MilestonePatchBody;
  new_plan: NewPlanSpec;
  new_task: NewTaskSpec;
  org_create: OrgCreateBody;
  org_list: OrgList;
  org_patch: OrgPatchBody;
  problem: Problem;
  project_create: ProjectCreateBody;
  project_detail: ProjectDetail;
  project_list: ProjectList;
  project_patch: ProjectPatchBody;
  project_plan: ProjectPlanBody;
  project_plan_accepted: ProjectPlanAccepted;
  provider_check: ProviderCheckResponse;
  provider_config: ProviderConfigView1;
  providers: Providers;
  reload: ReloadResult;
  replay_report: ReplayReport;
  report_detail: ReportDetail;
  report_list: ReportList;
  reports_notified: ReportsNotifiedResult;
  reports_read: ReportsReadBody;
  reports_read_result: ReportsReadResult;
  run_list: RunList;
  secret_put: SecretPutResult;
  secrets: SecretList;
  standing_rule_create: StandingRuleCreateBody;
  standing_rule_list: StandingRuleList;
  stream_daemon: DaemonSnapshot;
  stream_event: EventRow;
  stream_heartbeat: StreamHeartbeat;
  stream_hello: StreamHello;
  stream_reset: StreamReset;
  task: Task;
  task_detail: TaskDetail;
  task_list: TaskList;
  transition_result: TransitionResult;
}
/**
 * 1 アカウント（`GET /accounts` の要素、`POST /accounts` の応答）。
 */
export interface AccountView {
  /**
   * ADR-0025 D1: `"claude-code"` | `"codex"`。
   */
  adapter?: string;
  cooldown?: AccountCooldownView | null;
  /**
   * アカウントディレクトリの絶対パス（ログイン手順に要る。秘密の中身は含まない）。
   */
  dir: string;
  /**
   * `"not_logged_in" | "at_capacity" | "cooldown" | "five_hour_exhausted" | "seven_day_exhausted" | "rejected"`。
   */
  excluded_reason?: string | null;
  id: string;
  /**
   * 実行中の run の数。最初の tick 前は `0`。
   */
  in_use: number;
  last_check?: ProviderCheckView | null;
  /**
   * ログイン済みを示すファイル（claude-code は `.credentials.json`、codex は `auth.json`）の有無
   * （中身は読まない）。
   */
  logged_in: boolean;
  /**
   * ADR-0024 D7: 進行中のログイン中継があるか。
   */
  login_pending: boolean;
  /**
   * ADR-0024 D3 のスコア。除外なら `null`。
   */
  score?: number | null;
  stats: AccountStats;
  usage?: AccountUsageView | null;
}
export interface AccountCooldownView {
  /**
   * `"auth_failed" | "throttled" | "exhausted"`。
   */
  reason: string;
  until: string;
}
/**
 * ADR-0022 D2: 1 回の疎通確認の記録。
 */
export interface ProviderCheckView {
  /**
   * 確認した時刻（RFC 3339）。
   */
  at: string;
  /**
   * 人が読むための一行の手がかり（ワーカーの返答や失敗の理由。ADR-0022 M1）。無ければ `null`。
   */
  detail?: string | null;
  /**
   * `ok` / `auth_failed` / `throttled` / `spawn_failed`（`task_api::ProviderCheckResult` の serde 名）。
   */
  result: string;
}
/**
 * `WorkerStarted.account` / `WorkerFinished` から集計（task-api のメモリ内の観測値。再起動で再計算）。
 */
export interface AccountStats {
  done: number;
  error: number;
  input_tokens: number;
  output_tokens: number;
  runs: number;
}
/**
 * `RateLimitObservation` を RFC 3339 に直したもの。
 */
export interface AccountUsageView {
  five_hour?: RateWindowView | null;
  observed_at: string;
  seven_day?: RateWindowView | null;
  /**
   * `"run" | "check"`。
   */
  source: string;
  status?: string | null;
}
export interface RateWindowView {
  resets_at: string;
  utilization: number;
}
/**
 * `POST /accounts/{id}/check` の応答（ADR-0024 D6）。
 */
export interface AccountCheckResponse {
  checked_at: string;
  detail?: string | null;
  result: ProviderCheckResult;
  usage?: AccountUsageView | null;
}
/**
 * Phase 13（ADR-0024）: Claude アカウントのプール。
 */
export interface AccountList {
  /**
   * `adapter` → `id` の順。
   */
  items: AccountView[];
  max_runs_per_account: number;
  /**
   * `[accounts] claude_dir` の絶対パス。`[accounts]` が無ければ `null`。ADR-0025 D6: `roots["claude-code"]`
   * の別名として残す（後方互換）。
   */
  root?: string | null;
  /**
   * ADR-0025 D6: `"claude-code"` / `"codex"` → 設定されていればその絶対パス、無ければ `null`。
   */
  roots?: {
    [k: string]: string | null;
  };
}
/**
 * `POST /accounts/{id}/login/code` の応答。
 */
export interface AccountLoginResult {
  detail?: string | null;
  /**
   * `"ok" | "failed"`。
   */
  result: string;
}
/**
 * `POST /accounts/{id}/login` の応答（ADR-0024 D7、ADR-0025 D5）。
 */
export interface AccountLoginStart {
  /**
   * claude-code は 10 分後、codex は 15 分後（RFC 3339）。
   */
  expires_at: string;
  /**
   * `"paste_code"`（claude-code: URL を開いて認可し、表示されたコードを `login/code` に貼る）|
   * `"device_code"`（codex: URL を開いて `user_code` を入力する。GUI には貼り戻さない）。
   */
  kind?: string;
  url: string;
  /**
   * codex のみ。`login/code` には使わない（GUI が画面に出すだけ）。ログには出さない。
   */
  user_code?: string | null;
}
/**
 * `POST /tasks/{id}/answer` の本文。
 */
export interface AnswerBody {
  answer: string;
  expected_status?: Status | null;
}
/**
 * `POST /approvals/{id}/decide` の要求本文。
 */
export interface ApprovalDecideBody {
  answer: string;
  decision: Decision;
  /**
   * `decision = "standing"` のときだけ意味を持つ。`"node"`（既定）| `"all"`。
   */
  scope?: string | null;
}
/**
 * `POST /approvals/{id}/decide` の応答。`transition`（`task_ops::gate::TransitionResult`）は
 * `Deserialize` を持たないので、この型も応答専用（`Serialize` だけ）にする。
 */
export interface ApprovalDecideResult {
  approval: Approval;
  /**
   * `decision = "standing"` のときだけ `Some`。
   */
  standing_rule?: StandingRule | null;
  /**
   * 元の質問にタスクが紐づいていたときだけ `Some`（既存の「質問に答える」経路の結果）。
   */
  transition?: TransitionResult | null;
}
/**
 * 1 件の認可の要求（`approvals` テーブル。ADR-0033 D5）。
 */
export interface Approval {
  answer?: string | null;
  created_at: string;
  decided_at?: string | null;
  decision?: Decision | null;
  id: ApprovalId;
  /**
   * 聞いてきた組織のノード（`task.assignee`、無ければ秘書）。
   */
  node_id: string;
  /**
   * 案件（案件に紐づかない質問なら `None`）。
   */
  project_id?: ProjectId | null;
  question: string;
  /**
   * きっかけになったタスク（無いことは今回は無いが、`approval_decide` の後も残す前提で任意にしてある）。
   */
  task_id?: TaskId | null;
}
/**
 * 永続の認可 1 行（`standing_rules` テーブル。ADR-0033 D5）。
 */
export interface StandingRule {
  created_at: string;
  id: StandingRuleId;
  /**
   * `None` = 全員（どのノードの run にも注入される）。
   */
  node_id?: string | null;
  rule: string;
}
/**
 * 状態変更の結果（承認・却下・回答・取り消し共通）。
 */
export interface TransitionResult {
  /**
   * この遷移の伝播で `cancelled` になった、対象タスク以外のタスク（`docs/gui/api.md` §5.7）。
   */
  cascaded?: TaskRef[];
  from: Status;
  id: TaskId;
  reason: string;
  to: Status;
}
export interface TaskRef {
  /**
   * 今この状態で許される操作（ADR-0015 D4。GUI は §5.4 の規則を再実装しない）。
   */
  actions: Action[];
  id: TaskId;
  kind: TaskKind;
  status: Status;
  title: string;
}
/**
 * Phase 26（ADR-0033 D5）: 認可（`GET /approvals` と `POST /approvals/{id}/decide`）。
 */
export interface ApprovalList {
  items: Approval[];
}
/**
 * `GET /tasks/{id}/artifacts`。
 */
export interface ArtifactList {
  items: ArtifactView[];
}
export interface ArtifactView {
  artifact: ArtifactRef;
  exists: boolean;
  /**
   * パス検査に落ちた（ワークスペース外・symlink 越え・絶対パス等）。本体の取得は 403。
   */
  forbidden: boolean;
  /**
   * `ArtifactProduced` の出現順（0 始まり）。`GET /tasks/{id}/artifacts/{idx}` の添字。
   */
  idx: number;
  run_id: string;
  /**
   * 64 MiB 以下のときだけ計算する。
   */
  sha256_current?: string | null;
  /**
   * 記録値との一致。`exists = false` または未計算なら `null`。
   */
  sha256_matches?: boolean | null;
  size?: number | null;
  ts: string;
}
/**
 * DESIGN §4.4 の `ArtifactRef`。実体は `workspace/<task_id>/artifacts/` 配下。
 */
export interface ArtifactRef {
  kind: string;
  name: string;
  path: string;
  sha256: string;
}
/**
 * `POST /tasks/{id}/cancel` の本文。
 */
export interface CancelBody {
  expected_status?: Status | null;
}
/**
 * `POST /clusters/{id}/connect/code` の応答。コード・URL は含まない。
 */
export interface ClusterConnectResult {
  detail?: string | null;
  ok: boolean;
}
/**
 * ADR-0032 D5: `POST /clusters/{id}/connect` と `POST /clusters/{id}/connect/code` の応答。
 */
export interface ClusterConnectStart {
  /**
   * `kind = "needs_code"` のときだけ（RFC 3339）。
   */
  expires_at?: string | null;
  /**
   * `"connected"` | `"needs_code"`。
   */
  kind: string;
  /**
   * `kind = "needs_code"` のときだけ。ssh が出したプロンプト文字列（ユーザ名・ホスト名を含みうるので
   * ログには出さない。`GET /clusters` にも出さない。応答にだけ載る）。
   */
  prompt?: string | null;
}
/**
 * `GET /clusters`（ADR-0018 受け入れ条件8）。
 */
export interface Clusters {
  items: ClusterView[];
}
/**
 * 設定（`[[clusters]]`）とスナップショット（`ClusterLive`）を結合したもの。`env` の値は出さない。
 */
export interface ClusterView {
  /**
   * ADR-0032 D1: `"manual"` | `"publickey"` | `"totp"`（設定の `[[clusters]].auth` から）。
   */
  auth?: string;
  concurrency: number;
  /**
   * ADR-0032 D5: GUI 発の接続（`POST /clusters/{id}/connect`）が進行中か。スナップショットが無ければ `false`。
   */
  connect_pending?: boolean;
  /**
   * この tick で `ssh -O check` が成功したか。スナップショットが無ければ `null`。
   */
  connected?: boolean | null;
  /**
   * `cooldown_until − now`（秒）。過ぎていれば両方 `null`。
   */
  cooldown_remaining_secs?: number | null;
  /**
   * cooldown 中ならその終わり（RFC 3339）。
   */
  cooldown_until?: string | null;
  delete_on_push: boolean;
  /**
   * `env` のキー名だけ（昇順）。
   */
  env_keys: string[];
  /**
   * `setup` が 1 行以上あるか（中身は出さない）。
   */
  has_setup: boolean;
  /**
   * `~/.ssh/config` の `Host` 名。
   */
  host: string;
  id: string;
  /**
   * スナップショットが無ければ `null`。
   */
  in_use?: number | null;
  rsync_excludes: string[];
  /**
   * `"rsync"` | `"none"`。
   */
  sync: string;
}
/**
 * `GET /config`: `taskd.toml` の要約。env の値・トークンは含めない。taskd が起動時に作る。
 */
export interface ConfigView {
  api: ApiConfigView;
  /**
   * ADR-0018: `[[clusters]]` の要約（`env` はキー名だけ、`setup` は有無だけ）。
   */
  clusters?: ClusterConfigView[];
  config_path: string;
  /**
   * DB の絶対パス。
   */
  db: string;
  delegation?: DelegationLimits;
  error_cooldown_secs: number;
  /**
   * ADR-0027 D1: `[[genres]]` の要約。
   */
  genres?: GenreConfigView[];
  idle_timeout_secs: number;
  kill_grace_secs: number;
  lease_grace_secs: number;
  max_concurrency: number;
  max_requeues: number;
  plan_auto_accept: boolean;
  providers: ProviderConfigView[];
  retry_backoff_base_secs: number;
  retry_backoff_max_secs: number;
  review_timeout_secs: number;
  reviewer: ReviewerConfigView;
  /**
   * ADR-0016 D1: `[[roles]]` の要約（指示文の本文は出さない）。
   */
  roles?: RoleConfigView[];
  tick_ms: number;
  workspace_root: string;
}
export interface ApiConfigView {
  allowed_hosts: string[];
  auth_required: boolean;
  bind: string;
}
/**
 * `[[clusters]]` 1 行の要約（ADR-0018 D7: `env` の値は出さない）。
 */
export interface ClusterConfigView {
  /**
   * ADR-0032 D1: `"manual"` | `"publickey"` | `"totp"`。
   */
  auth?: string;
  concurrency: number;
  delete_on_push: boolean;
  /**
   * `env` のキー名だけ（昇順）。
   */
  env_keys: string[];
  /**
   * `setup` が 1 行以上あるか（中身は出さない）。
   */
  has_setup: boolean;
  /**
   * `~/.ssh/config` の `Host` 名。
   */
  host: string;
  id: string;
  rsync_excludes: string[];
  /**
   * `"rsync"` | `"none"`。
   */
  sync: string;
}
/**
 * ADR-0016 D2: `[delegation]` の上限。
 */
export interface DelegationLimits {
  /**
   * 1 run あたりの件数（複数の `delegate` をまたいで数える）。
   */
  max_delegate_per_run: number;
  /**
   * 木の深さ（根 = 1）。
   */
  max_tree_depth: number;
  /**
   * 木全体のワーカー run 数。
   */
  max_tree_runs: number;
  /**
   * ADR-0021 D4: 委譲した子が失敗したときの親の扱い。
   */
  on_child_failure: "retry_then_ask" | "ignore";
}
/**
 * `[[genres]]` 1 行の要約（ADR-0027 D1, ADR-0028 D1）。
 */
export interface GenreConfigView {
  /**
   * ADR-0028 D1: この分野で「できること」の自由記述。空なら省略される。
   */
  capabilities?: string[];
  default_role?: string | null;
  description: string;
  id: string;
  /**
   * ADR-0028 D1: この分野に渡すもの（目安）。空なら省略される。
   */
  input_artifacts?: string[];
  /**
   * ADR-0028 D1: この分野から返るもの（目安）。空なら省略される。
   */
  output_artifacts?: string[];
  /**
   * この分野に属する役割 id の一覧。
   */
  roles: string[];
}
export interface ProviderConfigView {
  /**
   * ADR-0024 D2: `[accounts]` のプールから選ぶか（既定 `false`）。
   */
  account_pool?: boolean;
  adapter: string;
  concurrency: number;
  /**
   * `[[providers]].env` のキー名だけ。
   */
  env_keys: string[];
  id: string;
  /**
   * 実効モデル（空なら `null`）。
   */
  model?: string | null;
  tiers: Tier[];
}
export interface ReviewerConfigView {
  adapter?: string | null;
  tier: Tier;
}
/**
 * `[[roles]]` 1 行の要約（ADR-0016 D1）。`instructions` は**本文を出さない**（プロンプトの中身は設定ファイルにだけ置く）。
 */
export interface RoleConfigView {
  adapter?: string | null;
  /**
   * 指示文が 1 文字以上あるか（中身は出さない）。
   */
  has_instructions: boolean;
  id: string;
  max_turns?: number | null;
  max_wall_secs?: number | null;
  tier?: Tier | null;
}
/**
 * `GET /daemon`。
 */
export interface DaemonView {
  now: string;
  /**
   * 最初の tick より前は `null`。
   */
  snapshot?: DaemonSnapshot | null;
}
export interface DaemonSnapshot {
  /**
   * ADR-0024/0025: プールのアカウント（`adapter` → `id` の順、id 昇順）。`[accounts]` が無ければ空。
   */
  accounts?: AccountLive[];
  /**
   * ADR-0024 D1/D5: `[accounts] claude_dir` の絶対パス（`[accounts]` が無ければ `None`）。
   * ADR-0025 D6: claude-code の根の別名として残す（`accounts_roots["claude-code"]` と同じ値）。
   */
  accounts_root?: string | null;
  /**
   * ADR-0025 D1/D6: アダプタごとの根ディレクトリ（`"claude-code"` / `"codex"` → 絶対パス。設定されていない
   * アダプタはキーごと無い）。古いスナップショットには無いので既定は空。
   */
  accounts_roots?: {
    [k: string]: string;
  };
  /**
   * ADR-0033 D5（Phase 26）: 未決定の認可（`approvals.decision IS NULL`）の件数。`reports` と同じ理由で
   * **API が応答を組むときに埋める**（ディスパッチャが送るスナップショットでは常に 0）。
   */
  approvals_pending?: number;
  /**
   * ADR-0023 D3: 委譲した子が終わるのを待っている親（`reviewing` のまま。id 昇順）。
   * 「自分の判定待ち」と区別するための観測値。古いスナップショットには無いので既定は空。
   */
  awaiting_children?: TaskId[];
  /**
   * 人間の承認待ちでレビューを延期している reviewing タスク。
   */
  awaiting_human: TaskId[];
  /**
   * ADR-0018: `[[clusters]]` の稼働状況（`id` 昇順）。第 2 段階で追加したので、古いスナップショットには無い。
   */
  clusters?: ClusterLive[];
  cooldowns: CooldownView[];
  hostname: string;
  in_flight: InFlight[];
  /**
   * 起動ごとの ULID（`GET /health` の `instance_id` と同じ）。
   */
  instance_id: string;
  last_tick_at: string;
  /**
   * ADR-0024 D1: `[accounts] max_runs_per_account`（`[accounts]` が無ければ `None`）。
   */
  max_runs_per_account?: number | null;
  pid: number;
  providers: ProviderLive[];
  /**
   * ADR-0033 D3（Phase 25）: 秘書レベルの未読の報告と通知の判定。**API が応答を組むときに埋める**
   * 唯一のフィールド（`last_notified_at` は `POST /reports/notified` が進める API プロセスの観測値で、
   * ディスパッチャは知らない）。ディスパッチャが送るスナップショットでは常に `None`。
   */
  reports?: ReportsLive | null;
  started_at: string;
  tick_ms: number;
  ticks: number;
  /**
   * 設定に合うプロバイダが無い ready タスク（この tick の判定）。
   */
  unroutable: TaskId[];
}
/**
 * ADR-0024/0025: プールの 1 アカウントの稼働状況（観測値。DB には書かない）。
 */
export interface AccountLive {
  /**
   * ADR-0025 D1: `"claude-code"` | `"codex"`。古いスナップショットには無いので既定は `"claude-code"`。
   */
  adapter?: string;
  cooldown?: AccountCooldownLive | null;
  /**
   * `"not_logged_in" | "at_capacity" | "cooldown" | "five_hour_exhausted" | "seven_day_exhausted" | "rejected"`。
   */
  excluded_reason?: string | null;
  id: string;
  /**
   * 実行中の run（ワーカー run + このアカウントを使う Reviewer run）の数。
   */
  in_use: number;
  last_check?: ProviderCheckView | null;
  /**
   * ログイン済みを示すファイル（claude-code は `.credentials.json`、codex は `auth.json`）の有無。
   */
  logged_in: boolean;
  /**
   * 進行中のログイン中継（ADR-0024 D7）があるか。
   */
  login_pending?: boolean;
  /**
   * ADR-0024 D3 のスコア。除外されていれば `None`。
   */
  score?: number | null;
  usage?: AccountUsageLive | null;
}
/**
 * アカウントの cooldown（Unix 秒）。
 */
export interface AccountCooldownLive {
  /**
   * `"auth_failed" | "throttled" | "exhausted"`。
   */
  reason: string;
  until: number;
}
/**
 * `RateLimitObservation` の観測値部分（Unix 秒のまま。壁時計の文字列化は task-api が行う）。
 */
export interface AccountUsageLive {
  five_hour?: RateWindow | null;
  observed_at: number;
  seven_day?: RateWindow | null;
  /**
   * `"run" | "check"`。
   */
  source: string;
  status?: string | null;
}
/**
 * 1 つの枠（5 時間 / 7 日）の観測値。
 */
export interface RateWindow {
  /**
   * 枠がリセットされる時刻（Unix 秒、`resetsAt`）
   */
  resets_at: number;
  /**
   * 0.0〜1.0（`unifiedWindows.<w>.utilization`）
   */
  utilization: number;
}
/**
 * クラスタ（`[[clusters]]` の行）の稼働状況（ADR-0018 D2 / D5）。`env` の値・`setup` の中身は含めない。
 */
export interface ClusterLive {
  /**
   * ADR-0032 D1: `"manual"` / `"publickey"` / `"totp"`。古いスナップショットには無いので既定は `"manual"`
   * （`taskd::config::ClusterConfig.auth` と同じ既定）。
   */
  auth?: string;
  concurrency: number;
  /**
   * ADR-0032 D4: GUI 発の接続（`POST /clusters/{id}/connect`）が進行中か。古いスナップショットには無いので既定は `false`。
   */
  connect_pending?: boolean;
  /**
   * この tick で `ssh -O check` が成功した（人が張った多重接続がある）。
   */
  connected: boolean;
  /**
   * 多重接続が無くて cooldown 中なら、その終わり（RFC 3339）。
   */
  cooldown_until?: string | null;
  /**
   * `~/.ssh/config` の `Host` 名。
   */
  host: string;
  id: string;
  /**
   * このクラスタで走っている run（ワーカー run + 判定）の数。
   */
  in_use: number;
}
/**
 * `task_dispatch::policy::Cooldown`（`Instant`）を壁時計に直したもの。
 */
export interface CooldownView {
  provider: string;
  /**
   * `"throttled" | "auth_failed" | "exhausted"`。
   */
  reason: string;
  until: string;
}
/**
 * 実行中の run（ワーカー run、またはプロバイダを使う Reviewer run）。
 */
export interface InFlight {
  kind: InFlightKind;
  provider: string;
  run_id: string;
  since: string;
  task_id: TaskId;
}
/**
 * プロバイダ（`[[providers]]` の行 = アカウント）の稼働状況。`env` の値は含めない。
 */
export interface ProviderLive {
  /**
   * ADR-0024 D2: `[accounts]` のプールから選ぶか。古いスナップショットには無いので既定 `false`。
   */
  account_pool?: boolean;
  adapter: string;
  concurrency: number;
  /**
   * `env` のキー名だけ（値は出さない）。古いスナップショットには無いので既定は空（ADR-0017 M4）。
   */
  env_keys?: string[];
  id: string;
  /**
   * 実行中の run と Reviewer run の合計。
   */
  in_use: number;
  /**
   * ADR-0022 D2: 直近の疎通確認（`POST /providers/{id}/check`）の結果。**メモリだけに持つ観測値**で、
   * taskd を再起動すると消える（イベントにも DB にも残さない）。一度も確認していなければ `None`。
   */
  last_check?: ProviderCheckView | null;
  /**
   * 実効モデル（空なら `None`）。
   */
  model?: string | null;
  tiers: Tier[];
}
/**
 * 未読の件数（`DaemonSnapshot.reports` と GUI の通知判定に使う観測値。ADR-0033 D3）。
 */
export interface ReportsLive {
  /**
   * 前回 GUI が通知した時刻（RFC 3339）。`POST /reports/notified` が進める。
   */
  last_notified_at?: string | null;
  /**
   * 「前回の通知から 2 時間以上経ち未読がある」か「`bad_news` の未読がある」。
   */
  notify_now: boolean;
  /**
   * そのうち `bad_news` の件数（0 でなければ即通知）。
   */
  unread_bad_news: number;
  /**
   * 秘書レベル（`level = 0`）の未読の件数。
   */
  unread_secretary: number;
}
/**
 * `POST /tasks/{id}/approve`、`POST /tasks/{id}/reject` の本文。
 */
export interface DecisionBody {
  expected_status?: Status | null;
  note?: string | null;
}
/**
 * `GET /tasks/{id}/events`、`GET /events`。
 */
export interface EventsPage {
  has_more: boolean;
  items: EventRow[];
}
/**
 * `events` テーブルの 1 行（ADR-0013 D6）。`id` はテーブル全体でのグローバル単調増加値。
 */
export interface EventRow {
  event: Event;
  id: number;
  seq: number;
  task_id: TaskId;
  /**
   * DB に保存された RFC 3339 文字列そのまま。
   */
  ts: string;
}
/**
 * DESIGN §4.1 の `Task`。
 */
export interface Task {
  acceptance: Criterion[];
  /**
   * ADR-0016 D3: true なら、委譲した子が全て終端になった後に集約 run を 1 回だけ行い `artifacts/summary.md` を作らせる。
   */
  aggregate?: boolean;
  /**
   * ADR-0033 D2: 割り当てられた組織のノード（`org_nodes.id`）。あれば `worker_hint` の解決で
   * 役割・分野より先に見る。無ければ従来どおり（互換）。
   */
  assignee?: string | null;
  attempts: number;
  budget: Budget;
  /**
   * ADR-0033 D4（Phase 24）: 対話由来のタスクなら、きっかけになった人の発言（`messages.id`）。
   * run が終わると、その結果が `assignee` のノードの返事として `messages` に入る。
   * **DB の列は増やさない**（`json` 列の中だけ。導入前のタスクには無いので任意）。
   */
  conversation?: MessageId | null;
  created_at: string;
  depends_on: TaskId[];
  /**
   * ADR-0027 D1: 分野名（自由記述。`[[genres]] id` と一致すれば既定の役割・プロンプトの説明が効く）。
   * 状態機械は見ない。導入前のタスクには無いので任意。
   */
  genre?: string | null;
  id: TaskId;
  inputs: ArtifactRef[];
  kind: TaskKind;
  lease?: Lease | null;
  /**
   * ADR-0033 D2: このタスクが属する途中目標（`project_id` の案件のもの）。
   */
  milestone_id?: MilestoneId | null;
  objective: string;
  parent_id?: TaskId | null;
  priority: number;
  /**
   * ADR-0033 D2: このタスクが属する案件。導入前のタスク・案件に属さないタスクには無い。
   */
  project_id?: ProjectId | null;
  /**
   * ADR-0016 D1: 役割名（自由記述。`[[roles]] id` と一致すれば既定と指示文が効く）。状態機械は見ない。
   * 導入前のタスクには無いので任意。
   */
  role?: string | null;
  status: Status;
  title: string;
  updated_at: string;
  worker_hint: WorkerHint;
  workspace: WorkspaceSpec;
}
/**
 * DESIGN §4.1 の `Criterion`。
 */
export interface Criterion {
  check: Check;
  text: string;
}
/**
 * DESIGN §4.1 の `Budget`。
 */
export interface Budget {
  max_retries: number;
  max_turns: number;
  max_wall_secs: number;
}
/**
 * DESIGN §4.1 の `Lease`。ADR-0002 D7: `expires_at` は
 * `budget.max_wall_secs + 猶予` から `acquire_lease` 呼び出し側が計算する。
 */
export interface Lease {
  expires_at: string;
  worker_run_id: string;
}
export interface WorkerHint {
  adapter?: string | null;
  tier: Tier;
}
/**
 * DESIGN §5.3 の `usage`。取れない項目は省略可。
 */
export interface Usage {
  input_tokens?: number | null;
  output_tokens?: number | null;
}
export interface Graph {
  edges: GraphEdge[];
  nodes: GraphNode[];
}
export interface GraphEdge {
  /**
   * タスクの一意識別子（ULID）。DESIGN §4.1。
   */
  from: string;
  /**
   * 常に `"depends_on"`。
   */
  kind: string;
  /**
   * タスクの一意識別子（ULID）。DESIGN §4.1。
   */
  to: string;
}
export interface GraphNode {
  id: TaskId;
  kind: TaskKind;
  parent_id?: TaskId | null;
  /**
   * ADR-0016 D1 の `Task.role`（GUI-R2: DAG のノードに役割のラベルを出すため）。
   */
  role?: string | null;
  status: Status;
  title: string;
}
/**
 * `GET /health`（無認証）。
 */
export interface Health {
  /**
   * 常に `"1"`。
   */
  api_version: string;
  db: DbInfo;
  instance_id: string;
  now: string;
  /**
   * `schema_migrations` の最大版数。
   */
  schema_version: number;
  started_at: string;
  taskd_version: string;
}
export interface DbInfo {
  busy_timeout_ms: number;
  /**
   * `PRAGMA journal_mode` の実測値（`"wal"` でなければ設定不備）。
   */
  journal_mode: string;
}
export interface Inbox {
  approvals: ApprovalItem[];
  attention: AttentionItem[];
  counts: InboxCounts;
  drafts: DraftGroup[];
  questions: QuestionItem[];
}
export interface ApprovalItem {
  approval: TaskRef;
  artifacts: ArtifactRef[];
  attempt?: number | null;
  criterion_idx?: number | null;
  criterion_text: string;
  evidence: EvidenceView[];
  last_run?: RunSummary | null;
  other_verdicts: VerdictView[];
  parent?: TaskRef | null;
  previous_decisions: ApprovalDecisionView[];
  requested_at: string;
}
/**
 * `task_worker::Evidence` と同じ形。
 */
export interface EvidenceView {
  command?: string | null;
  criterion: number;
  exit?: number | null;
  stdout_tail?: string | null;
}
export interface RunSummary {
  /**
   * プールのアカウント（ADR-0024 D4 / ADR-0025）。`WorkerStarted.account` がある run だけ。
   */
  account?: string | null;
  adapter: string;
  artifacts: number;
  /**
   * `runs/<run_id>/` のファイルの有無。task-ops は `None` を入れ、task-api が埋める。
   */
  files?: RunFiles | null;
  finished_at?: string | null;
  model: string;
  outcome?: RunOutcomeKind | null;
  outcome_text?: string | null;
  progress: number;
  provider?: string | null;
  reviewer_deferrals: number;
  /**
   * ワーカー run か Reviewer run か（ADR-0014 D1。イベントに `role` が無ければ `worker`）。
   */
  role: "worker" | "reviewer";
  run_id: string;
  started_at: string;
  usage?: Usage | null;
  verdicts: number;
}
export interface RunFiles {
  /**
   * ADR-0023 M1: `runs/<run_id>/prompt.txt`（claude-code / codex が実際に渡した文面）。fake には無い。
   */
  prompt?: boolean;
  /**
   * ADR-0023 D2: `runs/<run_id>/request.json`（ワーカーに渡した指示）。導入前の run には無いので既定は false。
   */
  request?: boolean;
  result: boolean;
  stderr: boolean;
  stdout: boolean;
}
export interface VerdictView {
  criterion_idx: number;
  pass: boolean;
  reason: string;
  run_id: string;
  ts: string;
}
export interface ApprovalDecisionView {
  approved: boolean;
  by: string;
  note?: string | null;
  ts: string;
}
export interface InboxCounts {
  approvals: number;
  attention: number;
  /**
   * status 名 → 件数（DB 全体）。
   */
  by_status: {
    [k: string]: number;
  };
  drafts: number;
  questions: number;
}
export interface DraftGroup {
  drafts: TaskSummary[];
  parent?: TaskRef | null;
  plan_summary?: string | null;
}
export interface TaskSummary {
  /**
   * 今この状態で許される操作（ADR-0015 D4）。
   */
  actions: Action[];
  adapter?: string | null;
  /**
   * ADR-0033 D2 の `Task.assignee`（組織のノード id。GUI-R3: 一覧に「誰の仕事か」を出すため）。
   */
  assignee?: string | null;
  attempts: number;
  backoff_until?: string | null;
  children: number;
  /**
   * 対話用タスク（人への返事のための run）か（GUI-R3: 仕事の木や一覧から隠せるように）。
   */
  conversation: boolean;
  created_at: string;
  depends_on: TaskId[];
  /**
   * ADR-0027 D1 の `Task.genre`（`role` と同じ理由で一覧に出す。`TaskDetail.genre` と同じ値）。
   */
  genre?: string | null;
  id: TaskId;
  kind: TaskKind;
  lease_expires_at?: string | null;
  max_retries: number;
  parent_id?: TaskId | null;
  pending_children: number;
  priority: number;
  /**
   * ADR-0016 D1 の `Task.role`（GUI-R2: 一覧の各行に役割のラベルを出すため。`TaskDetail.role` と同じ値）。
   */
  role?: string | null;
  status: Status;
  /**
   * GUI 監査 H4（Phase 29）: 裏方タスクの印（`"conversation"` | `"compaction"` | `"approval"` |
   * `"review"` | `null`）。`task_core::support_kind` の決定的な判定。GUI はこれで仕事の木から裏方を外せる。
   */
  support?: string | null;
  tier: Tier;
  title: string;
  updated_at: string;
}
export interface QuestionItem {
  /**
   * GUI 監査対応 Phase 29: 対応する未決の `approvals` の id（`POST /approvals/{id}/decide` へ
   * GUI が直接リンクできるように）。無ければ `null`（`approvals` の行がまだ無い、または既に決定済み）。
   */
  approval_id?: ApprovalId | null;
  asked_at?: string | null;
  previous: AnswerNote[];
  question: string;
  run_id?: string | null;
  task: TaskRef;
}
/**
 * `answers_from_events` の要素。`task_worker::Answer` と同じ形（フィールド名も同じ）。
 */
export interface AnswerNote {
  answer: string;
  question: string;
}
/**
 * GUI 監査対応 Phase 29 / H3（ADR-0033 D6）: 記憶を読む（`GET /org/{id}/memory`）。
 */
export interface MemoryView {
  /**
   * `notes.md` の全文（無ければ空文字列）。
   */
  notes: string;
  /**
   * `notes.md` の絶対パス（人がファイルを直接編集するため）。
   */
  notes_path: string;
  /**
   * `?project=` を指定したときだけ `Some`（その引き出し `projects/<project_id>.md` の全文、無ければ
   * 空文字列）。指定しなければ `null`。
   */
  project?: string | null;
  /**
   * `?project=` を指定したときだけ `Some`。指定しなければ `null`。
   */
  project_path?: string | null;
}
/**
 * `POST /org/{id}/messages` の応答（202）。返事は待たずに、GUI が `GET /org/{id}/messages` で拾う。
 */
export interface MessageAccepted {
  /**
   * 入った `role = "user"` の行の id。
   */
  message_id: string;
  /**
   * タスクの一意識別子（ULID）。DESIGN §4.1。
   */
  task_id: string;
}
/**
 * `GET /org/{id}/messages` の応答（古い順）。
 */
export interface MessageList {
  items: Message[];
}
/**
 * 対話の 1 行（`messages` テーブル。ADR-0033 D4）。
 */
export interface Message {
  created_at: string;
  id: MessageId;
  /**
   * 話し相手（`org_nodes.id`）。
   */
  node_id: string;
  /**
   * 案件（案件に紐づかない雑談なら `None`）。
   */
  project_id?: ProjectId | null;
  role: MessageRole;
  /**
   * `role = node` のとき、その返事を作った run（`Event::WorkerStarted.run_id`）。
   */
  run_id?: string | null;
  /**
   * この 1 往復を起こした対話用タスク（GUI からの依頼 R4 / Phase 24 の P-74。migration 0007）。
   * `role = user` の行にも `role = node` の行にも**同じ id** が入る。導入前の行は `None`。
   */
  task_id?: TaskId | null;
  text: string;
}
/**
 * Phase 24（ADR-0033 D4）: 対話（`POST /org/{id}/messages` と `GET /org/{id}/messages`）。
 */
export interface MessagePostBody {
  /**
   * この案件についての話なら案件の id（省略すると案件に紐づかない雑談になる）。
   */
  project_id?: ProjectId | null;
  /**
   * 本文（空白だけは 422）。
   */
  text: string;
}
/**
 * `POST /projects/{id}/milestones` の要求本文。`seq` はストアが採番する。
 */
export interface MilestoneCreateBody {
  description?: string | null;
  /**
   * 省略時は `proposed`（秘書が提案し、人が承認する。SPEC §7）。
   */
  status?: MilestoneStatus | null;
  title: string;
}
/**
 * `PATCH /milestones/{id}` の要求本文。
 */
export interface MilestonePatchBody {
  status: MilestoneStatus;
}
/**
 * `taskctl plan` から組み立てる新規 Plan タスクの指定。API の `POST /plans` の本文でもある（`docs/gui/api.md` §3.14）。
 */
export interface NewPlanSpec {
  /**
   * 大目標。1行目の先頭80文字が `title` になる。
   */
  goal: string;
  max_retries?: number;
  max_turns?: number;
  max_wall_secs?: number;
  priority?: number;
  /**
   * DESIGN §5.4 の `WorkerHint`。
   */
  tier?: "frontier" | "standard" | "cheap";
  workspace?: string | null;
}
/**
 * `taskctl add` から組み立てる新規タスクの指定。API の `POST /tasks` の本文でもある（`docs/gui/api.md` §3.4）。
 * 省略時の既定は `taskctl add` と同じ。
 */
export interface NewTaskSpec {
  acceptance: CriterionSpec[];
  /**
   * 省略時は役割の既定 → 指定なし。
   */
  adapter?: string | null;
  /**
   * ADR-0016 D3: 委譲した子が全て終端になった後に集約 run を 1 回行う。
   */
  aggregate?: boolean;
  /**
   * ADR-0033 D2: 割り当てる組織のノード（`org_nodes.id`）。既定の解決で役割・分野より先に見る。
   * 存在しないノードはエラー。
   */
  assignee?: string | null;
  /**
   * ADR-0018: 指定すると `WorkspaceSpec::Remote{cluster, path}` になり、コマンドはそのクラスタで実行される。
   * `workspace` がクラスタ側の作業ディレクトリ（既存プロジェクトでよい）。
   */
  cluster?: string | null;
  depends_on?: TaskId[];
  /**
   * ADR-0027 D1: 分野名（自由記述）。省略時は `role` の分野（`[[genres]] roles` に含む分野がちょうど
   * 1 つのとき）を継ぐ。`genres` が設定されていれば、知らない `genre` や `role` とその分野の不整合は
   * エラー（`genres` が空の設定では検証しない。分野は任意）。
   */
  genre?: string | null;
  /**
   * DESIGN §4.1 の `TaskKind`。
   */
  kind?: "plan" | "execute" | "review" | "approval";
  max_retries?: number;
  /**
   * 省略時は役割の既定 → 10。
   */
  max_turns?: number | null;
  /**
   * 省略時は役割の既定 → 600。
   */
  max_wall_secs?: number | null;
  /**
   * ADR-0033 D2: このタスクが属する途中目標。`project_id` と同じ案件のものであること。
   */
  milestone_id?: MilestoneId | null;
  objective: string;
  parent?: TaskId | null;
  priority?: number;
  /**
   * ADR-0033 D2: このタスクが属する案件。存在しない案件はエラー。
   */
  project_id?: ProjectId | null;
  /**
   * ADR-0016 D1: 役割名（自由記述）。`[[roles]]` にあれば省略値の既定と run 時の指示文が効く。
   */
  role?: string | null;
  /**
   * 省略時は役割の既定 → `standard`（ADR-0016 D1 / M3: タスクの値 > 役割の既定 > 全体の既定）。
   */
  tier?: Tier | null;
  title: string;
  workspace?: string | null;
}
/**
 * `POST /org` の要求本文（管理系）。
 */
export interface OrgCreateBody {
  brief?: string | null;
  genre?: string | null;
  id: string;
  kind: OrgKind;
  name: string;
  parent_id?: string | null;
  position?: number | null;
}
/**
 * Phase 23（ADR-0033 D1）: 組織（一つ、役割の木）。
 */
export interface OrgList {
  items: OrgNode[];
}
/**
 * 組織の 1 ノード（＝ SPEC §3.2 の「人」）。
 */
export interface OrgNode {
  /**
   * 担当の一言（プロンプトに前置きされる）。
   */
  brief?: string;
  created_at: string;
  /**
   * ADR-0027/0028 の `[[genres]] id`。その「人」が仕事に使うハーネスの束。部は持たなくてよい。
   */
  genre?: string | null;
  /**
   * 英小文字ケバブの id（`secretary` / `coding-frontend` 等）。設定の種とも API とも同じ文字列。
   */
  id: string;
  kind: OrgKind;
  name: string;
  /**
   * 親ノードの id。`secretary`（根）だけが `None`。
   */
  parent_id?: string | null;
  /**
   * 同じ親の中での並び順（GUI の組織図の表示順）。
   */
  position?: number;
  updated_at: string;
}
/**
 * `PATCH /org/{id}` の要求本文（管理系）。書いた項目だけを変える。
 * `genre` は `null` を書けば「分野なし」にできる（書かなければ今の値のまま）。
 */
export interface OrgPatchBody {
  brief?: string | null;
  genre?: string | null;
  kind?: OrgKind | null;
  name?: string | null;
  parent_id?: string | null;
  position?: number | null;
}
/**
 * RFC 9457 の problem details（`application/problem+json`）。`extra` は `code` ごとの付加フィールド。
 */
export interface Problem {
  code: string;
  detail: string;
  /**
   * `urn:taskd:request:<X-Request-Id>`。
   */
  instance: string;
  status: number;
  title: string;
  /**
   * `urn:taskd:problem:<code>`。
   */
  type: string;
  [k: string]: unknown;
}
/**
 * `POST /projects` の要求本文。作られた案件は `status = "proposed"`（秘書の返事待ち）。
 */
export interface ProjectCreateBody {
  request: string;
  title: string;
}
/**
 * `GET /projects/{id}` の応答。案件 + 途中目標 + その案件のタスクの要約（GUI の「仕事の木」用）。
 */
export interface ProjectDetail {
  milestones: Milestone[];
  project: Project;
  /**
   * 仕事の木を描くのに必要な最小限だけ（詳細は `GET /tasks/{id}`）。
   */
  tasks: ProjectTaskView[];
}
/**
 * 途中目標（ADR-0033 D2）。`seq` は案件の中での通し番号（1 始まり。ストアが採番する）。
 */
export interface Milestone {
  created_at: string;
  description?: string;
  id: MilestoneId;
  project_id: ProjectId;
  seq: number;
  status: MilestoneStatus;
  title: string;
  updated_at: string;
}
/**
 * 案件（SPEC §3.3）。仕事の木は `tasks WHERE project_id = ?`。
 */
export interface Project {
  created_at: string;
  id: ProjectId;
  /**
   * 人が投げた依頼文そのまま。
   */
  request: string;
  /**
   * 秘書の理解確認・方針（Phase 24 で秘書が書く）。
   */
  secretary_summary?: string | null;
  status: ProjectStatus;
  title: string;
  updated_at: string;
}
/**
 * 仕事の木の 1 ノード（ADR-0033 D2: DAG は既存の `parent_id` / `depends_on` がそのまま）。
 */
export interface ProjectTaskView {
  assignee?: string | null;
  /**
   * 対話用タスク（人への返事のための run）か。GUI は仕事の木から隠せる（GUI-R3）。
   */
  conversation: boolean;
  depends_on: TaskId[];
  id: TaskId;
  milestone_id?: MilestoneId | null;
  parent_id?: TaskId | null;
  status: Status;
  /**
   * GUI 監査 H4（Phase 29）: 裏方タスクの印（`TaskSummary.support` と同じ規則）。
   */
  support?: string | null;
  title: string;
}
/**
 * Phase 23（ADR-0033 D2）: 案件と途中目標。
 */
export interface ProjectList {
  items: Project[];
}
/**
 * `PATCH /projects/{id}` の要求本文。
 */
export interface ProjectPatchBody {
  status: ProjectStatus;
}
/**
 * GUI 監査対応 Phase 29（ADR-0033 D4 追記）: 分解を起こす（`POST /projects/{id}/plan`）。
 */
export interface ProjectPlanBody {
  /**
   * 分解の対象にする途中目標。省略すると `approved` / `in_progress` のものを文脈として渡すだけで、
   * 特定の 1 件をこのタスクに紐づけない。
   */
  milestone_id?: MilestoneId | null;
  /**
   * 人の一言（任意）。
   */
  note?: string | null;
}
/**
 * `POST /projects/{id}/plan` の応答（202）。
 */
export interface ProjectPlanAccepted {
  task_id: TaskId;
}
/**
 * `POST /api/v1/providers/{id}/check` の応答（ADR-0017 D2）。
 */
export interface ProviderCheckResponse {
  checked_at: string;
  /**
   * ADR-0022 M1: 人が読むための一行の手がかり（ワーカーの返答、失敗の理由）。無ければ `null`。
   */
  detail?: string | null;
  result: ProviderCheckResult;
}
/**
 * `POST /api/v1/providers` と `PATCH /api/v1/providers/{id}` の応答（ADR-0017）。
 */
export interface ProviderConfigView1 {
  /**
   * ADR-0024 D2: `[accounts]` のプールから選ぶか（既定 `false`）。
   */
  account_pool?: boolean;
  adapter: string;
  concurrency: number;
  /**
   * `[[providers]].env` のキー名だけ。
   */
  env_keys: string[];
  id: string;
  /**
   * 実効モデル（空なら `null`）。
   */
  model?: string | null;
  tiers: Tier[];
}
/**
 * `GET /providers`。
 */
export interface Providers {
  items: ProviderView[];
}
export interface ProviderView {
  /**
   * ADR-0024 D2: `[accounts]` のプールから選ぶか（既定 `false`）。
   */
  account_pool?: boolean;
  adapter: string;
  concurrency: number;
  /**
   * スナップショットが無い、または cooldown 中でなければ `null`。
   */
  cooldown?: CooldownView | null;
  /**
   * `env` のキー名だけ（値は出さない）。
   */
  env_keys: string[];
  id: string;
  /**
   * スナップショットが無ければ `null`。
   */
  in_use?: number | null;
  /**
   * ADR-0022 D2: 直近の `POST /providers/{id}/check` の結果（`{at, result}`）。まだ確認していない、
   * または taskd を再起動した後は `null`（メモリだけに持つ観測値）。
   */
  last_check?: ProviderCheckView | null;
  model?: string | null;
  stats: ProviderStats;
  tiers: Tier[];
}
/**
 * プロバイダ別の run 集計（task-api のメモリ内の観測値。再起動で再計算）。
 */
export interface ProviderStats {
  /**
   * `WorkerFinished.ts` の UTC 日付で直近 30 日（昇順。run の無い日は現れない）。
   */
  by_day: DailyUsage[];
  done: number;
  error: number;
  input_tokens: number;
  lease_expired: number;
  output_tokens: number;
  question: number;
  requeue: number;
  /**
   * `WorkerStarted` の数（実行中を含む）。
   */
  runs: number;
}
export interface DailyUsage {
  /**
   * `YYYY-MM-DD`（UTC）。
   */
  day: string;
  input_tokens: number;
  output_tokens: number;
  /**
   * その日に終わった run の数。
   */
  runs: number;
}
/**
 * `POST /api/v1/reload` の応答（ADR-0017 D1）。
 */
export interface ReloadResult {
  reloaded: boolean;
}
/**
 * `replay` の結果。
 */
export interface ReplayReport {
  mismatches: ReplayMismatch[];
  tasks: number;
}
/**
 * `replay` が検出した 1 件の食い違い。
 */
export interface ReplayMismatch {
  /**
   * `"status"` または `"attempts"`。
   */
  field: string;
  /**
   * `events` から再構築した値。
   */
  replayed: string;
  /**
   * `tasks` テーブルに保存されている値。
   */
  stored: string;
  task_id: TaskId;
}
/**
 * `GET /reports/{id}` の応答（`sources` の中身も展開して返す）。
 */
export interface ReportDetail {
  report: Report;
  /**
   * `report.sources` の順に引いた元の報告（見つからなかったものは飛ばす）。
   */
  sources_expanded: Report[];
}
/**
 * 1 件の報告。
 */
export interface Report {
  body?: string;
  created_at: string;
  headline: string;
  id: ReportId;
  kind: ReportKind;
  /**
   * 組織の木の深さ（秘書 = 0）。GUI は `level = 0` を「人が見る報告」として扱う。
   */
  level: number;
  /**
   * 報告した組織のノード（`org_nodes.id`）。
   */
  node_id: string;
  /**
   * 案件。`None` は「案件なし」（クラスタの障害など、案件に紐づかない悪い知らせ）。DB でも NULL
   * （migration 0007 で NOT NULL を外した。ADR-0034 D1 の「将来」の項）。
   */
  project_id?: ProjectId | null;
  read_at?: string | null;
  /**
   * 元になった報告の id（まとめなら子の報告、悪い知らせの複製なら 1 段下の報告）。
   */
  sources?: ReportId[];
  /**
   * 元になったタスク（まとめの報告では、そのまとめの run のタスク）。
   */
  task_id?: TaskId | null;
}
/**
 * Phase 25（ADR-0033 D3）: 報告（生成は決定的、圧縮は別 run）。
 */
export interface ReportList {
  items: Report[];
}
/**
 * `POST /reports/notified` の応答。
 */
export interface ReportsNotifiedResult {
  /**
   * 進めた後の通知時刻（RFC 3339）。
   */
  last_notified_at: string;
}
/**
 * `POST /reports/read` の本文。
 */
export interface ReportsReadBody {
  ids: string[];
}
/**
 * `POST /reports/read` の応答。
 */
export interface ReportsReadResult {
  /**
   * 未読から既読に変わった件数。
   */
  updated: number;
}
/**
 * `GET /tasks/{id}/runs`。
 */
export interface RunList {
  runs: RunSummary[];
}
/**
 * `PUT /secrets/{id}` の応答。値は含まない。
 */
export interface SecretPutResult {
  fingerprint: string;
  id: string;
  updated_at: string;
}
/**
 * Phase 20（ADR-0030）: GUI から預かる秘密（API キー等）。`GET /secrets` と `PUT /secrets/{id}` の応答。
 */
export interface SecretList {
  /**
   * `[secrets] dir` の絶対パス。
   */
  dir?: string | null;
  /**
   * ファイルがある id を id 昇順、続けて未設定（`env_from_secrets` が参照しているだけ）の id を id 昇順。
   */
  items: SecretView[];
}
/**
 * 1 秘密（値は決して含まない）。
 */
export interface SecretView {
  /**
   * 値の sha256 の先頭 8 桁（値そのものは復元できない）。値が無ければ `null`。
   */
  fingerprint?: string | null;
  id: string;
  /**
   * ファイルの mtime（RFC 3339）。**まだ値が入っていない**（設定が参照しているだけ）なら `null`。
   */
  updated_at?: string | null;
  /**
   * 設定（`env_from_secrets`）から導いた、この秘密を使っている場所。
   */
  used_by: SecretUse[];
}
/**
 * `SecretView.used_by` の 1 要素。
 */
export interface SecretUse {
  /**
   * 流し込む環境変数名。
   */
  env: string;
  /**
   * `scope = "adapter"` ならアダプタ種別（`"claude-code"` 等）、`"provider"` ならプロバイダ id。
   */
  name: string;
  /**
   * `"adapter" | "provider"`。
   */
  scope: string;
}
/**
 * `POST /standing-rules` の要求本文。
 */
export interface StandingRuleCreateBody {
  /**
   * 省略すると全員向け（`node_id = NULL`）。
   */
  node_id?: string | null;
  rule: string;
}
/**
 * Phase 26（ADR-0033 D5）: 永続の認可（`GET /standing-rules` と `POST /standing-rules`）。
 */
export interface StandingRuleList {
  items: StandingRule[];
}
/**
 * SSE `event: heartbeat`。
 */
export interface StreamHeartbeat {
  now: string;
}
/**
 * SSE `event: hello`。
 */
export interface StreamHello {
  /**
   * 送信開始位置（この id より後の `task.event` を送る）。
   */
  cursor: number;
  daemon?: DaemonSnapshot | null;
  now: string;
}
/**
 * SSE `event: reset`。クライアントは全体を再取得する。
 */
export interface StreamReset {
  /**
   * 以後の送信開始位置（最新の id）。
   */
  cursor: number;
  /**
   * `"cursor_too_old"` | `"cursor_ahead"`。
   */
  reason: string;
}
/**
 * `taskctl show --json` と `GET /api/v1/tasks/{id}` の本体。
 */
export interface TaskDetail {
  actions: Action[];
  answers: AnswerNote[];
  approvals: ApprovalLink[];
  children: TaskRef[];
  /**
   * ADR-0018: `WorkspaceSpec::Remote` のクラスタ（`[[clusters]] id`）。ローカルのタスクは `null`。
   */
  cluster?: string | null;
  criteria: CriterionView[];
  /**
   * ADR-0016 D2: 各 run が `delegate` で作った子（`Event::Delegated` の順）。
   */
  delegated: DelegatedView[];
  dependencies: TaskRef[];
  dependents: TaskRef[];
  /**
   * ADR-0027 D1: `Task.genre`（`role` と同じ理由で最上位にも出す）。
   */
  genre?: string | null;
  latest_question?: string | null;
  prior_review: ReviewNote[];
  /**
   * ADR-0016 D1: `Task.role`（GUI の表示用に最上位にも出す）。
   */
  role?: string | null;
  runs: RunSummary[];
  task: Task;
  timers: Timers;
  worker_run_hint?: string | null;
  /**
   * 手元の作業ディレクトリ（絶対パス）。`WorkspaceSpec::Remote` では写し `workspace_root/<task_id>`（run のログはここ。ADR-0018 D1）。
   */
  workspace_dir?: string | null;
  /**
   * ADR-0019 D2: `sync = "worktree"` のクラスタで動くタスクの worktree。人はここを見て diff / commit する。
   */
  worktree?: WorktreeView | null;
}
export interface ApprovalLink {
  approval: TaskRef;
  attempt?: number | null;
  criterion_idx?: number | null;
  decided?: ApprovalDecisionView | null;
}
export interface CriterionView {
  approval?: ApprovalLink | null;
  check: Check;
  idx: number;
  latest_verdict?: VerdictView | null;
  text: string;
}
/**
 * ADR-0016 D2: 1 回の `delegate`（`Event::Delegated`）の要約。
 */
export interface DelegatedView {
  run_id: string;
  /**
   * 子の現在の状態。既に存在しない ID は落とす。
   */
  tasks: TaskRef[];
  /**
   * イベントの ts（`EventRow.ts`）。
   */
  ts: string;
}
/**
 * `prior_review_from_events` の要素。`task_worker::PriorReview` と同じ形（フィールド名も同じ）。
 */
export interface ReviewNote {
  criterion: number;
  pass: boolean;
  reason: string;
}
export interface Timers {
  backoff_until?: string | null;
  consecutive_requeues: number;
  consecutive_reviewer_requeues: number;
  lease_expires_at?: string | null;
  max_requeues: number;
  now: string;
}
/**
 * ADR-0019 D2: クラスタ側の worktree（taskd はここだけを触り、commit はしない）。
 */
export interface WorktreeView {
  /**
   * worktree のブランチ（`taskd/<task_id>`）。taskd は commit しないので、変更は作業ツリーに残る。
   */
  branch: string;
  /**
   * worktree のパス（クラスタ上）。
   */
  dir: string;
  /**
   * 元のリポジトリ（`WorkspaceSpec::Remote.path`）。
   */
  project: string;
}
export interface TaskList {
  /**
   * status 名 → 件数（フィルタに関係なく DB 全体。0 件の status は現れない）。
   */
  counts_by_status: {
    [k: string]: number;
  };
  items: TaskSummary[];
  next_cursor?: string | null;
  total: number;
}
